#!/usr/bin/env python3
"""Build the IAC A/B phase sequence contract.

This isolates the source-proven ring sequence from the broader IAC output
contract. It does not define Enable behavior, park/reset behavior, idle strategy,
or create an IAC writer.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

FIELDS = [
    "stage", "pc", "mnemonic", "operands", "state_before", "direction_bit",
    "state_after", "ab_bits_before", "ab_bits_after", "actual_count_delta",
    "l004c_shadow_update", "l3062_write", "candidate_role",
    "physical_direction_pending", "confidence", "notes",
]

ROWS = [
    {
        "stage": "actual_desired_compare",
        "pc": "0x91C2-0x91C6",
        "mnemonic": "LDAA/CMPA/BNE",
        "operands": "L0007 / L0008 / L91CC",
        "state_before": "any",
        "direction_bit": "unchanged if equal",
        "state_after": "hold if actual == desired",
        "ab_bits_before": "L000A bits2/3",
        "ab_bits_after": "held",
        "actual_count_delta": "0 if equal",
        "l004c_shadow_update": "refreshed later from L000A bits2/3",
        "l3062_write": "via LF400 latch service",
        "candidate_role": "desired_actual_compare",
        "physical_direction_pending": "yes",
        "confidence": "high_static",
        "notes": "L0007 actual is compared against L0008 desired before any phase change",
    },
    {
        "stage": "direction0_count_update",
        "pc": "0x91D4-0x91DD",
        "mnemonic": "ANDB/BRSET/INCA",
        "operands": "#$FE / L000A,#$01 / INCA",
        "state_before": "actual < desired",
        "direction_bit": "0",
        "state_after": "phase ring advances if direction already matched",
        "ab_bits_before": "current L000A bits2/3",
        "ab_bits_after": "next direction0 state",
        "actual_count_delta": "+1 after direction matched; 0 on first reversal",
        "l004c_shadow_update": "yes after phase update",
        "l3062_write": "later full-byte latch",
        "candidate_role": "direction0_step_candidate",
        "physical_direction_pending": "open_or_close_pending",
        "confidence": "high_static",
        "notes": "count-positive direction is source-proven but physical open/close is bench-gated",
    },
    {
        "stage": "direction1_count_update",
        "pc": "0x91DF-0x91E6",
        "mnemonic": "ORAB/BRCLR/DECA/STAA",
        "operands": "#$01 / L000A,#$01 / DECA / L0007",
        "state_before": "actual > desired",
        "direction_bit": "1",
        "state_after": "phase ring reverses if direction already matched",
        "ab_bits_before": "current L000A bits2/3",
        "ab_bits_after": "next direction1 state",
        "actual_count_delta": "-1 after direction matched; 0 on first reversal",
        "l004c_shadow_update": "yes after phase update",
        "l3062_write": "later full-byte latch",
        "candidate_role": "direction1_step_candidate",
        "physical_direction_pending": "open_or_close_pending",
        "confidence": "high_static",
        "notes": "count-negative direction is source-proven but physical open/close is bench-gated",
    },
    {
        "stage": "dir0_none_to_a",
        "pc": "0x91E8-0x91FA",
        "mnemonic": "BRCLR/BITB/EORB",
        "operands": "L000A,#$0C / #$01 / #$04",
        "state_before": "none",
        "direction_bit": "0",
        "state_after": "A candidate",
        "ab_bits_before": "0x00",
        "ab_bits_after": "0x04",
        "actual_count_delta": "+1 after direction matched",
        "l004c_shadow_update": "bits2/3 become 0x04",
        "l3062_write": "bits2/3 candidate later become 0x04",
        "candidate_role": "iac_phase_ring_forward",
        "physical_direction_pending": "bit2_physical_A_pending",
        "confidence": "high_static",
        "notes": "direction bit0 clear toggles bit2 from no-coil state",
    },
    {
        "stage": "dir0_a_to_ab",
        "pc": "0x91E8-0x91FA",
        "mnemonic": "BITB/EORB",
        "operands": "#$01 / #$08",
        "state_before": "A candidate",
        "direction_bit": "0",
        "state_after": "A+B candidate",
        "ab_bits_before": "0x04",
        "ab_bits_after": "0x0C",
        "actual_count_delta": "+1",
        "l004c_shadow_update": "bits2/3 become 0x0C",
        "l3062_write": "bits2/3 candidate later become 0x0C",
        "candidate_role": "iac_phase_ring_forward",
        "physical_direction_pending": "bit2_bit3_physical_order_pending",
        "confidence": "high_static",
        "notes": "one-bit intermediate transition is in CPU register/RAM before shadow commit, not direct hardware BSET/BCLR",
    },
    {
        "stage": "dir0_ab_to_b",
        "pc": "0x91E8-0x91FA",
        "mnemonic": "BRSET/BITB/EORB",
        "operands": "L000A,#$0C / #$01 / #$04",
        "state_before": "A+B candidate",
        "direction_bit": "0",
        "state_after": "B candidate",
        "ab_bits_before": "0x0C",
        "ab_bits_after": "0x08",
        "actual_count_delta": "+1",
        "l004c_shadow_update": "bits2/3 become 0x08",
        "l3062_write": "bits2/3 candidate later become 0x08",
        "candidate_role": "iac_phase_ring_forward",
        "physical_direction_pending": "bit3_physical_B_pending",
        "confidence": "high_static",
        "notes": "both-on state transitions by toggling bit2 in direction0 path",
    },
    {
        "stage": "dir0_b_to_none",
        "pc": "0x91E8-0x91FE",
        "mnemonic": "BITB/EORB",
        "operands": "#$01 / #$08",
        "state_before": "B candidate",
        "direction_bit": "0",
        "state_after": "none",
        "ab_bits_before": "0x08",
        "ab_bits_after": "0x00",
        "actual_count_delta": "+1",
        "l004c_shadow_update": "bits2/3 become 0x00",
        "l3062_write": "bits2/3 candidate later become 0x00",
        "candidate_role": "iac_phase_ring_forward",
        "physical_direction_pending": "yes",
        "confidence": "high_static",
        "notes": "completes direction0 four-state ring",
    },
    {
        "stage": "dir1_none_to_b",
        "pc": "0x91E8-0x91FE",
        "mnemonic": "BRCLR/BITB/EORB",
        "operands": "L000A,#$0C / #$01 / #$08",
        "state_before": "none",
        "direction_bit": "1",
        "state_after": "B candidate",
        "ab_bits_before": "0x00",
        "ab_bits_after": "0x08",
        "actual_count_delta": "-1 after direction matched",
        "l004c_shadow_update": "bits2/3 become 0x08",
        "l3062_write": "bits2/3 candidate later become 0x08",
        "candidate_role": "iac_phase_ring_reverse",
        "physical_direction_pending": "bit3_physical_B_pending",
        "confidence": "high_static",
        "notes": "direction bit0 set chooses the opposite neighbor from no-coil state",
    },
    {
        "stage": "dir1_b_to_ab",
        "pc": "0x91E8-0x91FA",
        "mnemonic": "BITB/EORB",
        "operands": "#$01 / #$04",
        "state_before": "B candidate",
        "direction_bit": "1",
        "state_after": "A+B candidate",
        "ab_bits_before": "0x08",
        "ab_bits_after": "0x0C",
        "actual_count_delta": "-1",
        "l004c_shadow_update": "bits2/3 become 0x0C",
        "l3062_write": "bits2/3 candidate later become 0x0C",
        "candidate_role": "iac_phase_ring_reverse",
        "physical_direction_pending": "bit_order_pending",
        "confidence": "high_static",
        "notes": "reverse ring enters both-on state from B candidate",
    },
    {
        "stage": "dir1_ab_to_a",
        "pc": "0x91E8-0x91FE",
        "mnemonic": "BRSET/BITB/EORB",
        "operands": "L000A,#$0C / #$01 / #$08",
        "state_before": "A+B candidate",
        "direction_bit": "1",
        "state_after": "A candidate",
        "ab_bits_before": "0x0C",
        "ab_bits_after": "0x04",
        "actual_count_delta": "-1",
        "l004c_shadow_update": "bits2/3 become 0x04",
        "l3062_write": "bits2/3 candidate later become 0x04",
        "candidate_role": "iac_phase_ring_reverse",
        "physical_direction_pending": "bit2_physical_A_pending",
        "confidence": "high_static",
        "notes": "both-on state transitions by toggling bit3 in direction1 path",
    },
    {
        "stage": "dir1_a_to_none",
        "pc": "0x91E8-0x91FA",
        "mnemonic": "BITB/EORB",
        "operands": "#$01 / #$04",
        "state_before": "A candidate",
        "direction_bit": "1",
        "state_after": "none",
        "ab_bits_before": "0x04",
        "ab_bits_after": "0x00",
        "actual_count_delta": "-1",
        "l004c_shadow_update": "bits2/3 become 0x00",
        "l3062_write": "bits2/3 candidate later become 0x00",
        "candidate_role": "iac_phase_ring_reverse",
        "physical_direction_pending": "yes",
        "confidence": "high_static",
        "notes": "completes direction1 four-state ring",
    },
    {
        "stage": "shadow_to_latch",
        "pc": "0x9203-0x920A;0xF40F-0xF411",
        "mnemonic": "ANDA/ANDB/ABA/STAA;LDAA/STAA",
        "operands": "#$E3/#$1C/L004C; L004C/L3062",
        "state_before": "new L000A bits2/3",
        "direction_bit": "not output directly",
        "state_after": "L004C bits2/3 then L3062 bits2/3 candidate",
        "ab_bits_before": "new L000A bits2/3",
        "ab_bits_after": "L004C/L3062 bits2/3 candidate",
        "actual_count_delta": "already applied before latch update",
        "l004c_shadow_update": "masked full-field update",
        "l3062_write": "full-byte write",
        "candidate_role": "phase_latch_atomicity",
        "physical_direction_pending": "hardware pin mapping pending",
        "confidence": "high_static_for_source_medium_for_physical_pins",
        "notes": "normal source path does not use direct hardware BSET/BCLR for A/B phase bits",
    },
]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def resolve(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else repo_root() / p


def write_csv(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(ROWS)


def write_md(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# IAC Phase Sequence Contract",
        "",
        "## Purpose",
        "",
        "Document the IAC A/B ring sequence used to move the stepper driver one step at a time.",
        "",
        "This contract does not define Enable behavior, park/reset behavior, idle strategy, or desired IAC calculation. It does not create an IAC writer.",
        "",
        "## Proven Source State",
        "",
        "| Symbol | Role |",
        "|---|---|",
        "| `L0007` | actual/present IAC position |",
        "| `L0008` | desired/target IAC position |",
        "| `L000A bit0` | direction candidate |",
        "| `L000A bit2` | A candidate |",
        "| `L000A bit3` | B candidate |",
        "| `L004C bits2/3` | output shadow |",
        "| `L3062` | hardware latch write via `L004C` service |",
        "",
        "## Static Ring",
        "",
        "Bit values:",
        "",
        "```text",
        "none = 0x00 on bits2/3",
        "A    = 0x04",
        "B    = 0x08",
        "A+B  = 0x0C",
        "```",
        "",
        "Direction bit clear:",
        "",
        "```text",
        "none -> A -> A+B -> B -> none",
        "0x00 -> 0x04 -> 0x0C -> 0x08 -> 0x00",
        "```",
        "",
        "Direction bit set:",
        "",
        "```text",
        "none -> B -> A+B -> A -> none",
        "0x00 -> 0x08 -> 0x0C -> 0x04 -> 0x00",
        "```",
        "",
        "Bench still has to decide whether source `A` is physically A or B at the driver pins, and whether count increment means open or closed airflow.",
        "",
        "## Source Sequence",
        "",
        "```text",
        "0x91C2  LDAA L0007       ; actual/present position",
        "0x91C4  CMPA L0008       ; compare actual to desired",
        "0x91C6  BNE L91CC        ; equal means no step/count change",
        "",
        "0x91D4  BCC L91DF        ; actual >= desired path",
        "0x91D6  ANDB #$FE        ; direction bit0 clear candidate",
        "0x91DC  INCA             ; actual count +1 after direction matched",
        "",
        "0x91DF  ORAB #$01        ; direction bit0 set candidate",
        "0x91E5  DECA             ; actual count -1 after direction matched",
        "0x91E6  STAA L0007       ; commit actual count",
        "",
        "0x91E8  BRSET L000A,#$0C,L91F6",
        "0x91EC  BRCLR L000A,#$0C,L91F6",
        "0x91F0  BITB #$01        ; choose ring neighbor from direction",
        "0x91FA  EORB #$04        ; toggle bit2/A candidate",
        "0x91FE  EORB #$08        ; toggle bit3/B candidate",
        "0x9200  STAB L000A       ; commit phase state",
        "```",
        "",
        "## Phase Transition Table",
        "",
        "| Direction bit | State before | A/B bits before | State after | A/B bits after | Count delta |",
        "|---:|---|---:|---|---:|---|",
        "| 0 | none | `0x00` | A | `0x04` | `+1` after direction matched |",
        "| 0 | A | `0x04` | A+B | `0x0C` | `+1` |",
        "| 0 | A+B | `0x0C` | B | `0x08` | `+1` |",
        "| 0 | B | `0x08` | none | `0x00` | `+1` |",
        "| 1 | none | `0x00` | B | `0x08` | `-1` after direction matched |",
        "| 1 | B | `0x08` | A+B | `0x0C` | `-1` |",
        "| 1 | A+B | `0x0C` | A | `0x04` | `-1` |",
        "| 1 | A | `0x04` | none | `0x00` | `-1` |",
        "",
        "Direction reversal can update `L000A bit0` before the actual count is changed. Treat the first reversal edge as a possible zero-count-delta phase/authority change until bench confirms behavior.",
        "",
        "## Output Shadow / Latch Path",
        "",
        "The phase bits are not written directly with hardware `BSET/BCLR` in the normal path.",
        "",
        "```text",
        "0x9203  LDAA L004C",
        "0x9205  ANDA #$E3      ; clear L004C bits2/3/4",
        "0x9207  ANDB #$1C      ; isolate L000A bits2/3/4",
        "0x9209  ABA            ; merge",
        "0x920A  STAA L004C     ; output shadow update",
        "",
        "0xF40F  LDAA L004C",
        "0xF411  STAA L3062     ; full-byte hardware latch write",
        "```",
        "",
        "Phase atomicity is therefore statically classified as shadow full-field update followed by full-byte latch write. Physical pin timing remains bench-gated.",
        "",
        "## Contract Rows",
        "",
        "| Stage | PC | Direction | Before | After | Count delta | Role | Confidence |",
        "|---|---|---:|---|---|---|---|---|",
    ]
    for row in ROWS:
        lines.append(
            f"| {row['stage']} | `{row['pc']}` | {row['direction_bit']} | {row['state_before']} | {row['state_after']} | {row['actual_count_delta']} | {row['candidate_role']} | {row['confidence']} |"
        )
    lines += [
        "",
        "## Required New-OS Behavior",
        "",
        "A future IAC module must reproduce or explicitly replace:",
        "",
        "1. no-step hold when `actual == desired`",
        "2. direction-bit selection from desired/actual sign",
        "3. safe direction reversal before count update",
        "4. four-state A/B ring sequence",
        "5. shadow update of A/B bits",
        "6. full latch write path to the physical driver input",
        "",
        "## Open Bench Questions",
        "",
        "- Is bit2 physically A and bit3 physically B, or swapped?",
        "- Does actual count increment open or close the IAC?",
        "- Does one latch write produce a clean atomic A/B transition at the driver input?",
        "- Does every source step correspond to one physical motor step?",
        "- Does `L3062` update immediately after `L004C`, or at a delayed output-service cadence?",
        "",
        "## Out Of Scope For This Contract",
        "",
        "```text",
        "Enable/fault behavior",
        "park/reset/home behavior",
        "desired IAC calculation",
        "idle-speed strategy",
        "step cadence/rate-limit equation",
        "IAC writer implementation",
        "```",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--source", default="source/31/BMHM_HAC_ORG_7100_to_end.asm")
    p.add_argument("--iac", default="maps/contracts/iac_idle_air_output_contract.csv")
    p.add_argument("--out-md", required=True)
    p.add_argument("--out-csv", required=True)
    args = p.parse_args()
    write_csv(resolve(args.out_csv))
    write_md(resolve(args.out_md))
    print(f"IAC_PHASE_SEQUENCE: wrote {len(ROWS)} phase rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
