#!/usr/bin/env python3
"""Build the LA906 spark rolling-state model contract.

This documents persistence/continuity state around $3FF6/$3FDC/L01EC and the
$3FEC->$3FE4 mirror. It does not generate a spark writer.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

ROLLING_ROWS = [
    {
        "stage": "entry_anchor_read",
        "pc": "0xAB97",
        "mnemonic": "ADDD",
        "operands": "L3FF6",
        "state_symbol": "L3FF6",
        "state_address": "0x3FF6",
        "read_or_write": "read",
        "input_value": "D_AB97 timing-domain input",
        "operation": "add rolling anchor / EST fall counter to LA906 input",
        "output_value": "D = D_AB97 + L3FF6",
        "candidate_role": "rolling_event_anchor",
        "persistence_required": "likely_yes",
        "recompute_possible": "unknown_pending_bench",
        "hardware_feedback_dependency": "possible_asic_counter_state",
        "required_for_minimal_os": "likely_yes_if_la906_path_retained",
        "confidence": "medium_static",
        "notes": "first LA906 state touch; value is later rewritten at 0xABC8",
    },
    {
        "stage": "anchor_difference_for_3fe8",
        "pc": "0xABA4",
        "mnemonic": "SUBD",
        "operands": "L3FF6",
        "state_symbol": "L3FF6",
        "state_address": "0x3FF6",
        "read_or_write": "read",
        "input_value": "D intermediate and same rolling anchor",
        "operation": "subtract rolling anchor before first ASIC timing write",
        "output_value": "D for $3FE8 path",
        "candidate_role": "previous_est_edge_or_anchor_delta",
        "persistence_required": "likely_yes",
        "recompute_possible": "unknown_pending_bench",
        "hardware_feedback_dependency": "possible_asic_counter_state",
        "required_for_minimal_os": "bench_classify",
        "confidence": "medium_static",
        "notes": "$3FE8 command is not independent of $3FF6 state",
    },
    {
        "stage": "first_command_write_context",
        "pc": "0xABAA",
        "mnemonic": "STD",
        "operands": "L3FE8",
        "state_symbol": "L3FE8",
        "state_address": "0x3FE8",
        "read_or_write": "write",
        "input_value": "D after $3FF6 arithmetic",
        "operation": "write first paired timing command candidate",
        "output_value": "$3FE8 = D",
        "candidate_role": "next_est_edge_or_timing_command_1",
        "persistence_required": "runtime_write_required_pending_bench",
        "recompute_possible": "yes_from_current_bridge_state_if_model_known",
        "hardware_feedback_dependency": "asic_command_register",
        "required_for_minimal_os": "likely_yes_pending_bench",
        "confidence": "medium_static",
        "notes": "included as command output context for rolling-state model",
    },
    {
        "stage": "prior_state_read_for_3fe6",
        "pc": "0xABB0",
        "mnemonic": "ADDD",
        "operands": "L3FDC",
        "state_symbol": "L3FDC",
        "state_address": "0x3FDC",
        "read_or_write": "read",
        "input_value": "D after $3FE8 path",
        "operation": "add prior rolling timing state before second command",
        "output_value": "D = D + L3FDC",
        "candidate_role": "previous_est_edge_or_paired_edge_state",
        "persistence_required": "likely_yes",
        "recompute_possible": "unknown_pending_bench",
        "hardware_feedback_dependency": "possible_asic_or_software_prediction_state",
        "required_for_minimal_os": "likely_yes_if_paired_edge_model_confirmed",
        "confidence": "medium_static",
        "notes": "$3FDC is later overwritten from L01EC-derived X at 0xABC0",
    },
    {
        "stage": "work_term_subtract_for_3fe6",
        "pc": "0xABB3",
        "mnemonic": "SUBD",
        "operands": "L01EC",
        "state_symbol": "L01EC",
        "state_address": "0x01EC",
        "read_or_write": "read",
        "input_value": "D after $3FDC add",
        "operation": "subtract timing correction/work-period term before second command",
        "output_value": "D for $3FE6 path",
        "candidate_role": "dwell_or_latency_offset",
        "persistence_required": "likely_yes_as_work_term",
        "recompute_possible": "possible_from_period/latency_if_model_known",
        "hardware_feedback_dependency": "software_prediction_state",
        "required_for_minimal_os": "bench_classify",
        "confidence": "medium_static",
        "notes": "L01EC is critical because it is immediately before $3FE6 write",
    },
    {
        "stage": "work_term_load_for_state_update",
        "pc": "0xABB7",
        "mnemonic": "LDX",
        "operands": "L01EC",
        "state_symbol": "L01EC",
        "state_address": "0x01EC",
        "read_or_write": "read",
        "input_value": "L01EC",
        "operation": "load work term into X for $3FDC update",
        "output_value": "X = L01EC",
        "candidate_role": "software_prediction_state",
        "persistence_required": "yes_if_3fdc_update_required",
        "recompute_possible": "possible_from_current_period_if_model_known",
        "hardware_feedback_dependency": "software_prediction_state",
        "required_for_minimal_os": "likely_yes_pending_bench",
        "confidence": "medium_static",
        "notes": "explains STX L3FDC source at 0xABC0",
    },
    {
        "stage": "second_command_write_context",
        "pc": "0xABBA",
        "mnemonic": "STD",
        "operands": "L3FE6",
        "state_symbol": "L3FE6",
        "state_address": "0x3FE6",
        "read_or_write": "write",
        "input_value": "D after $3FDC/L01EC math",
        "operation": "write second paired timing command candidate",
        "output_value": "$3FE6 = D",
        "candidate_role": "next_est_edge_or_timing_command_2",
        "persistence_required": "runtime_write_required_pending_bench",
        "recompute_possible": "yes_from_current_bridge_state_if_model_known",
        "hardware_feedback_dependency": "asic_command_register",
        "required_for_minimal_os": "likely_yes_pending_bench",
        "confidence": "medium_static",
        "notes": "included as second command output context for rolling-state model",
    },
    {
        "stage": "update_prior_state",
        "pc": "0xABC0",
        "mnemonic": "STX",
        "operands": "L3FDC",
        "state_symbol": "L3FDC",
        "state_address": "0x3FDC",
        "read_or_write": "write",
        "input_value": "X = L01EC",
        "operation": "persist current work term as next event prior state",
        "output_value": "$3FDC = L01EC",
        "candidate_role": "software_prediction_state",
        "persistence_required": "likely_yes",
        "recompute_possible": "maybe_from_current_L01EC_each_event",
        "hardware_feedback_dependency": "software_prediction_written_to_asic_window",
        "required_for_minimal_os": "likely_yes_if_3fdc_read_path_required",
        "confidence": "medium_static",
        "notes": "$3FDC is both read before $3FE6 and updated after $3FE6",
    },
    {
        "stage": "update_event_anchor",
        "pc": "0xABC8",
        "mnemonic": "STD",
        "operands": "L3FF6",
        "state_symbol": "L3FF6",
        "state_address": "0x3FF6",
        "read_or_write": "write",
        "input_value": "D restored/recomputed in LA906 path",
        "operation": "persist next rolling anchor / EST fall counter",
        "output_value": "$3FF6 = D",
        "candidate_role": "rolling_event_anchor",
        "persistence_required": "likely_yes",
        "recompute_possible": "unknown_pending_bench",
        "hardware_feedback_dependency": "software_prediction_or_asic_counter_sync",
        "required_for_minimal_os": "likely_yes_if_la906_path_retained",
        "confidence": "medium_static",
        "notes": "read twice earlier, then rewritten; high-value rolling-state candidate",
    },
    {
        "stage": "feedback_read",
        "pc": "0xAC28",
        "mnemonic": "LDX",
        "operands": "L3FEC",
        "state_symbol": "L3FEC",
        "state_address": "0x3FEC",
        "read_or_write": "read",
        "input_value": "$3FEC ASIC source/status/capture",
        "operation": "read hardware feedback/status source",
        "output_value": "X = $3FEC",
        "candidate_role": "hardware_capture_feedback",
        "persistence_required": "unknown_pending_bench",
        "recompute_possible": "no_if_real_hardware_feedback",
        "hardware_feedback_dependency": "yes",
        "required_for_minimal_os": "bench_classify",
        "confidence": "medium_static",
        "notes": "read source for immediate $3FE4 mirror/ack write",
    },
    {
        "stage": "feedback_mirror_ack",
        "pc": "0xAC2E",
        "mnemonic": "STX",
        "operands": "L3FE4",
        "state_symbol": "L3FE4",
        "state_address": "0x3FE4",
        "read_or_write": "write",
        "input_value": "X = $3FEC",
        "operation": "mirror hardware feedback/status to companion register",
        "output_value": "$3FE4 = $3FEC",
        "candidate_role": "asic_ack_state",
        "persistence_required": "likely_if_ack_required",
        "recompute_possible": "no_if_ack_must_mirror_hardware_value",
        "hardware_feedback_dependency": "yes",
        "required_for_minimal_os": "likely_yes_until_bench_disproves",
        "confidence": "medium_static",
        "notes": "suspicious feedback/ack mini-contract following rolling-state writes",
    },
    {
        "stage": "period_source_context",
        "pc": "0xAB8E",
        "mnemonic": "SUBD",
        "operands": "L3FC0",
        "state_symbol": "L3FC0",
        "state_address": "0x3FC0",
        "read_or_write": "read",
        "input_value": "pre-LA906 conversion value",
        "operation": "subtract hardware period/event anchor before D_AB97 pack/shift",
        "output_value": "pre-D_AB97 timing-domain value",
        "candidate_role": "hardware_capture_feedback",
        "persistence_required": "context_required_for_conversion",
        "recompute_possible": "no_if_hardware_period_capture",
        "hardware_feedback_dependency": "yes",
        "required_for_minimal_os": "owned_by_conversion_equation_not_rolling_update",
        "confidence": "medium_static",
        "notes": "included for boundary context; not updated inside LA906 output sequence",
    },
]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def resolve_path(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else repo_root() / p


def touch_required(path: str | Path) -> None:
    p = resolve_path(path)
    if not p.exists():
        raise FileNotFoundError(p)


def write_csv(out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    fields = ["stage", "pc", "mnemonic", "operands", "state_symbol", "state_address", "read_or_write", "input_value", "operation", "output_value", "candidate_role", "persistence_required", "recompute_possible", "hardware_feedback_dependency", "required_for_minimal_os", "confidence", "notes"]
    with out.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(ROLLING_ROWS)


def write_md(out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    md = [
        "# Spark Rolling State Model",
        "",
        "## Purpose",
        "",
        "Model the rolling timing state used by `LA906` between spark/EST events.",
        "",
        "This is the persistence/continuity contract. It does **not** create a spark writer.",
        "",
        "## Scope",
        "",
        "This contract explains the persistent state around:",
        "",
        "- `$3FF6`",
        "- `$3FDC`",
        "- `$01EC`",
        "- `$3FE8`",
        "- `$3FE6`",
        "- `$3FEC → $3FE4`",
        "",
        "Secondary boundary/context terms:",
        "",
        "- `$3FC0`",
        "- `L005F/L0060`",
        "- `L01EE/L01EF`",
        "- `L0201`",
        "- `L004F bit0`",
        "",
        "## Known Static Sequence",
        "",
        "```text",
        "D_AB97 + $3FF6       → timing state",
        "...",
        "STD $3FE8",
        "",
        "D + $3FDC - $01EC    → timing state",
        "...",
        "STD $3FE6",
        "",
        "STX $3FDC",
        "STD $3FF6",
        "",
        "LDX $3FEC",
        "STX $3FE4",
        "```",
        "",
        "## Candidate Model",
        "",
        "Static evidence suggests:",
        "",
        "```text",
        "$3FF6 = rolling timing anchor / EST fall counter candidate",
        "$3FDC = rolling timing state / prior edge candidate",
        "$01EC = latency/work-period correction term",
        "$3FE8 = first paired ASIC timing command",
        "$3FE6 = second paired ASIC timing command",
        "$3FEC = ASIC feedback/status/capture",
        "$3FE4 = mirror/ack target",
        "```",
        "",
        "## State Rows",
        "",
        "| Stage | PC | Instruction | State | Access | Candidate role | Persistence | Recompute? | Required? |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in ROLLING_ROWS:
        inst = f"{r['mnemonic']} {r['operands']}".strip()
        md.append(f"| {r['stage']} | `{r['pc']}` | `{inst}` | `{r['state_symbol']}` | {r['read_or_write']} | {r['candidate_role']} | {r['persistence_required']} | {r['recompute_possible']} | {r['required_for_minimal_os']} |")
    md += [
        "",
        "## Register/State Interpretation",
        "",
        "### `$3FF6/$3FF7`",
        "",
        "`$3FF6` is read at the start of the bridge, subtracted again before `$3FE8`, and then rewritten at the end. Static evidence strongly suggests it is not a one-shot command register. It behaves like a rolling event anchor, previous/next EST fall counter, or hardware-synchronized timing base.",
        "",
        "### `$3FDC/$3FDD`",
        "",
        "`$3FDC` is read before the `$3FE6` command calculation and then rewritten from `X`, where `X` was loaded from `L01EC`. That makes it look like prior-edge or paired-edge rolling state, not a simple mode register.",
        "",
        "### `L01EC/L01ED`",
        "",
        "`L01EC` is subtracted immediately before `$3FE6`, then loaded into `X` and persisted into `$3FDC`. Static evidence makes it a high-priority dwell/latency/work-period correction candidate. It may be recomputable, but only after its physical meaning is known.",
        "",
        "### `$3FE8/$3FE9` and `$3FE6/$3FE7`",
        "",
        "These appear to be paired timing-output writes. `$3FE8` is produced from the `$3FF6` relationship; `$3FE6` is produced from the `$3FDC - L01EC` relationship.",
        "",
        "### `$3FEC → $3FE4`",
        "",
        "The read/mirror sequence is suspicious enough to treat as required until bench testing says otherwise. If it is an ACK/capture handshake, a minimal OS cannot synthesize it without reading the real hardware source.",
        "",
        "## Required Questions",
        "",
        "- Does `$3FF6` represent the previous event anchor, next event anchor, or a fall-edge counter?",
        "- Does `$3FDC` represent a prior EST edge, a dwell-related edge, or an ASIC feedback copy?",
        "- Is `$01EC` a latency term, dwell term, or period correction?",
        "- Can a minimal OS recompute `$3FF6/$3FDC` each loop, or must it preserve continuity?",
        "- Is `$3FEC → $3FE4` required every event?",
        "- Which state must be initialized before the first run spark event?",
        "",
        "## Current Static Classification",
        "",
        "```text",
        "ROLL-A ($3FF6 required rolling event anchor):",
        "  strongly supported statically; read/subtract/update pattern.",
        "",
        "ROLL-B ($3FDC required prior/paired-edge state):",
        "  strongly supported statically; read before $3FE6 and update from L01EC.",
        "",
        "ROLL-C (L01EC required timing/dwell/latency correction):",
        "  strongly supported statically; subtract before $3FE6 and source for $3FDC update.",
        "",
        "ROLL-D ($3FEC->$3FE4 feedback/ack):",
        "  plausible; explicit read/mirror pair, bench required.",
        "",
        "ROLL-E (state recomputable each event):",
        "  possible only after L01EC/$3FF6/$3FDC units are known; not safe to assume.",
        "",
        "ROLL-F (static model incomplete):",
        "  possible until scoped/bench traced.",
        "```",
        "",
        "## Minimal-OS Implication",
        "",
        "If rolling state is required, the future spark module must be split into:",
        "",
        "```text",
        "SPARK_INIT_STATE",
        "SPARK_CONVERT_DEGREES_TO_TIME",
        "SPARK_UPDATE_ROLLING_STATE",
        "SPARK_ASIC_HANDOFF",
        "```",
        "",
        "Current expectation:",
        "",
        "```text",
        "$3FF6 is probably not optional.",
        "$3FDC is probably not optional.",
        "$3FE8/$3FE6 are probably a paired output.",
        "$3FEC->$3FE4 is suspicious enough to treat as required until bench says otherwise.",
        "```",
        "",
        "## Next Contract",
        "",
        "Before any provisional spark handoff stub, document first-event/init behavior:",
        "",
        "```text",
        "SPARK_INIT_STATE.md",
        "```",
    ]
    out.write_text("\n".join(md), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", default="source/31/BMHM_HAC_ORG_7100_to_end.asm")
    ap.add_argument("--la906", default="maps/contracts/spark_la906_output_sequence.csv")
    ap.add_argument("--timebase", default="maps/contracts/spark_timebase_period_contract.csv")
    ap.add_argument("--equation", default="maps/contracts/spark_conversion_equation.csv")
    ap.add_argument("--out-md", required=True)
    ap.add_argument("--out-csv", required=True)
    args = ap.parse_args()

    for dep in [args.source, args.la906, args.timebase, args.equation]:
        touch_required(dep)
    write_csv(resolve_path(args.out_csv))
    write_md(resolve_path(args.out_md))
    print(f"rolling state rows: {len(ROLLING_ROWS)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
