#!/usr/bin/env python3
"""Build the spark init-state contract.

This documents first-event / crank-to-run seed state required before the LA906
spark handoff can be trusted. It does not generate a spark writer.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

INIT_ROWS = [
    {
        "stage": "global_asic_clear",
        "pc": "0x715B",
        "mnemonic": "STD",
        "operands": "0,X",
        "state_symbol": "$3FC0-$3FF8 even words",
        "state_address": "0x3FC0:0x3FFA",
        "read_or_write": "write_loop",
        "value_source": "D=$0000",
        "routine_label": "init_clear_loop_candidate",
        "init_context": "key_on_or_reset_init",
        "before_first_la906": "yes",
        "crank_or_run": "pre_crank_or_pre_run",
        "candidate_role": "global_clear",
        "required_for_minimal_os": "likely_yes_global_asic_safe_default",
        "confidence": "medium_high_static",
        "notes": "clears even ASIC words from $3FC0 through before $3FFA; includes $3FE4/$3FE6/$3FE8/$3FDC/$3FEC/$3FF6",
    },
    {
        "stage": "period_capture_read",
        "pc": "0xA5E5",
        "mnemonic": "LDD",
        "operands": "L3FC0",
        "state_symbol": "L3FC0",
        "state_address": "0x3FC0",
        "read_or_write": "read",
        "value_source": "ASIC last DRP/ref period counter",
        "routine_label": "LA5E5",
        "init_context": "period_basis_formation",
        "before_first_la906": "yes_if_executed_before_run_spark",
        "crank_or_run": "crank_or_run_period_tracking",
        "candidate_role": "first_ref_capture",
        "required_for_minimal_os": "yes_valid_period_basis_required",
        "confidence": "medium_static",
        "notes": "commented LAST DRP PERIOD CNTR in prior contracts; source for software period basis",
    },
    {
        "stage": "period_basis_seed",
        "pc": "0xA5E8",
        "mnemonic": "STD",
        "operands": "L005F",
        "state_symbol": "L005F/L0060",
        "state_address": "0x005F",
        "read_or_write": "write",
        "value_source": "D from L3FC0",
        "routine_label": "LA5E5",
        "init_context": "period_basis_formation",
        "before_first_la906": "yes_if_executed_before_run_spark",
        "crank_or_run": "crank_or_run_period_tracking",
        "candidate_role": "period_basis_seed",
        "required_for_minimal_os": "yes_before_conversion_equation",
        "confidence": "medium_static",
        "notes": "seeds LF550 multiplicand used later as spark period basis",
    },
    {
        "stage": "period_basis_safety_fallback",
        "pc": "0xA5FC",
        "mnemonic": "STD",
        "operands": "L005F",
        "state_symbol": "L005F/L0060",
        "state_address": "0x005F",
        "read_or_write": "write",
        "value_source": "16-bit RPM/period derived value",
        "routine_label": "LA5E5",
        "init_context": "period_basis_formation_or_fallback",
        "before_first_la906": "yes_if_used_before_run_spark",
        "crank_or_run": "crank_or_run_period_tracking",
        "candidate_role": "period_basis_seed",
        "required_for_minimal_os": "yes_valid_period_or_safe_fallback_required",
        "confidence": "medium_static",
        "notes": "commented SAVE 16 BIT RPM VALUE in prior dependency pass; needs exact branch context before locking",
    },
    {
        "stage": "l01ec_seed_write",
        "pc": "0xA6EC",
        "mnemonic": "STD",
        "operands": "L01EC",
        "state_symbol": "L01EC/L01ED",
        "state_address": "0x01EC",
        "read_or_write": "write",
        "value_source": "D from timing correction path",
        "routine_label": "LA6E3",
        "init_context": "timing_work_term_seed",
        "before_first_la906": "yes_if_executed_before_la906",
        "crank_or_run": "crank_or_run_period_tracking",
        "candidate_role": "latency_seed",
        "required_for_minimal_os": "likely_yes_before_first_3fe6",
        "confidence": "medium_static",
        "notes": "first known L01EC write before LA906-side subtract; exact physical term pending",
    },
    {
        "stage": "l01ec_refine_read_subtract",
        "pc": "0xA6F5",
        "mnemonic": "SUBD",
        "operands": "L01EC",
        "state_symbol": "L01EC/L01ED",
        "state_address": "0x01EC",
        "read_or_write": "read",
        "value_source": "current L01EC work term",
        "routine_label": "LA6E3",
        "init_context": "timing_work_term_refine",
        "before_first_la906": "yes_if_executed_before_la906",
        "crank_or_run": "crank_or_run_period_tracking",
        "candidate_role": "latency_seed",
        "required_for_minimal_os": "likely_yes_if_stock_model_retained",
        "confidence": "medium_static",
        "notes": "L01EC is refined using period/correction math before later LA906 use",
    },
    {
        "stage": "l01ec_refine_write",
        "pc": "0xA6FD",
        "mnemonic": "STD",
        "operands": "L01EC",
        "state_symbol": "L01EC/L01ED",
        "state_address": "0x01EC",
        "read_or_write": "write",
        "value_source": "D refined timing term",
        "routine_label": "LA6E3",
        "init_context": "timing_work_term_refine",
        "before_first_la906": "yes_if_executed_before_la906",
        "crank_or_run": "crank_or_run_period_tracking",
        "candidate_role": "latency_seed",
        "required_for_minimal_os": "likely_yes_before_first_3fe6",
        "confidence": "medium_static",
        "notes": "latest L01EC seed candidate before LA906 subtract/update path",
    },
    {
        "stage": "spark_offset_sign_seed",
        "pc": "0xAB44",
        "mnemonic": "BCLR",
        "operands": "L004F,#$01",
        "state_symbol": "L004F bit0",
        "state_address": "0x004F",
        "read_or_write": "write_bit",
        "value_source": "clear sign state",
        "routine_label": "LAB3E",
        "init_context": "per_la906_conversion_entry",
        "before_first_la906": "immediately_before_conversion",
        "crank_or_run": "run_spark_path",
        "candidate_role": "safe_default",
        "required_for_minimal_os": "yes_if_stock_sign_model_retained",
        "confidence": "high_static",
        "notes": "clears sign before L01EE sign/magnitude handling; 1=retard, 0=advance",
    },
    {
        "stage": "spark_offset_sign_set_if_retard",
        "pc": "0xAB4C",
        "mnemonic": "BSET",
        "operands": "L004F,#$01",
        "state_symbol": "L004F bit0",
        "state_address": "0x004F",
        "read_or_write": "write_bit",
        "value_source": "negative L01EE path",
        "routine_label": "LAB3E",
        "init_context": "per_la906_conversion_entry",
        "before_first_la906": "immediately_before_conversion",
        "crank_or_run": "run_spark_path",
        "candidate_role": "safe_default",
        "required_for_minimal_os": "yes_if_stock_sign_model_retained",
        "confidence": "high_static",
        "notes": "sets retard sign bit before LF550/output postprocess path",
    },
    {
        "stage": "first_la906_anchor_dependency",
        "pc": "0xAB97",
        "mnemonic": "ADDD",
        "operands": "L3FF6",
        "state_symbol": "L3FF6/L3FF7",
        "state_address": "0x3FF6",
        "read_or_write": "read",
        "value_source": "existing rolling anchor",
        "routine_label": "LAB84",
        "init_context": "first_la906_run_update",
        "before_first_la906": "no_this_is_first_dependency",
        "crank_or_run": "run_spark_path",
        "candidate_role": "rolling_anchor_seed",
        "required_for_minimal_os": "must_be_valid_before_this_read",
        "confidence": "high_static_dependency_medium_init_unknown",
        "notes": "no separate non-LA906 seed identified yet besides global clear; bench must determine first valid value",
    },
    {
        "stage": "first_la906_prior_edge_dependency",
        "pc": "0xABB0",
        "mnemonic": "ADDD",
        "operands": "L3FDC",
        "state_symbol": "L3FDC/L3FDD",
        "state_address": "0x3FDC",
        "read_or_write": "read",
        "value_source": "existing prior/paired-edge state",
        "routine_label": "LABA2",
        "init_context": "first_la906_run_update",
        "before_first_la906": "no_this_is_first_dependency",
        "crank_or_run": "run_spark_path",
        "candidate_role": "prior_edge_seed",
        "required_for_minimal_os": "must_be_valid_before_this_read",
        "confidence": "high_static_dependency_medium_init_unknown",
        "notes": "global clear seeds zero; unknown whether zero is valid first-run seed",
    },
    {
        "stage": "first_output_command_1",
        "pc": "0xABAA",
        "mnemonic": "STD",
        "operands": "L3FE8",
        "state_symbol": "L3FE8/L3FE9",
        "state_address": "0x3FE8",
        "read_or_write": "write",
        "value_source": "D from first LA906 compute",
        "routine_label": "LABA2",
        "init_context": "first_la906_run_update",
        "before_first_la906": "no_output_of_first_update",
        "crank_or_run": "run_spark_path",
        "candidate_role": "first_run_spark_seed",
        "required_for_minimal_os": "yes_if_la906_path_confirmed",
        "confidence": "medium_static_pending_bench",
        "notes": "first paired timing command candidate after init state is consumed",
    },
    {
        "stage": "first_output_command_2",
        "pc": "0xABBA",
        "mnemonic": "STD",
        "operands": "L3FE6",
        "state_symbol": "L3FE6/L3FE7",
        "state_address": "0x3FE6",
        "read_or_write": "write",
        "value_source": "D from second LA906 compute",
        "routine_label": "LABA2",
        "init_context": "first_la906_run_update",
        "before_first_la906": "no_output_of_first_update",
        "crank_or_run": "run_spark_path",
        "candidate_role": "first_run_spark_seed",
        "required_for_minimal_os": "yes_if_la906_path_confirmed",
        "confidence": "medium_static_pending_bench",
        "notes": "second paired timing command candidate after init state is consumed",
    },
    {
        "stage": "rolling_prior_edge_update_after_first",
        "pc": "0xABC0",
        "mnemonic": "STX",
        "operands": "L3FDC",
        "state_symbol": "L3FDC/L3FDD",
        "state_address": "0x3FDC",
        "read_or_write": "write",
        "value_source": "X = L01EC",
        "routine_label": "LABA2",
        "init_context": "first_la906_run_update",
        "before_first_la906": "no_after_first_commands",
        "crank_or_run": "run_spark_path",
        "candidate_role": "prior_edge_seed",
        "required_for_minimal_os": "yes_for_second_and_later_events",
        "confidence": "medium_static",
        "notes": "after first event, $3FDC is seeded for next event from L01EC",
    },
    {
        "stage": "rolling_anchor_update_after_first",
        "pc": "0xABC8",
        "mnemonic": "STD",
        "operands": "L3FF6",
        "state_symbol": "L3FF6/L3FF7",
        "state_address": "0x3FF6",
        "read_or_write": "write",
        "value_source": "D from LA906 path",
        "routine_label": "LABA2",
        "init_context": "first_la906_run_update",
        "before_first_la906": "no_after_first_commands",
        "crank_or_run": "run_spark_path",
        "candidate_role": "rolling_anchor_seed",
        "required_for_minimal_os": "yes_for_second_and_later_events",
        "confidence": "medium_static",
        "notes": "after first event, $3FF6 is seeded for next event by LA906 itself",
    },
    {
        "stage": "mirror_ack_first_event",
        "pc": "0xAC28/0xAC2E",
        "mnemonic": "LDX/STX",
        "operands": "L3FEC -> L3FE4",
        "state_symbol": "L3FEC/L3FE4",
        "state_address": "0x3FEC->0x3FE4",
        "read_or_write": "read_then_write",
        "value_source": "X = hardware feedback/status from $3FEC",
        "routine_label": "LAC25",
        "init_context": "first_la906_run_update_or_ack",
        "before_first_la906": "no_after_commands_in_sequence",
        "crank_or_run": "run_spark_path",
        "candidate_role": "mirror_ack_seed",
        "required_for_minimal_os": "likely_yes_until_bench_disproves",
        "confidence": "medium_static_pending_bench",
        "notes": "may acknowledge first valid state or mirror capture/status for next event",
    },
]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def resolve_path(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else repo_root() / p


def touch_required(path: str | Path) -> None:
    p = resolve_path(path)
    if not p.exists():
        raise FileNotFoundError(p)


def write_csv(out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    fields = ["stage", "pc", "mnemonic", "operands", "state_symbol", "state_address", "read_or_write", "value_source", "routine_label", "init_context", "before_first_la906", "crank_or_run", "candidate_role", "required_for_minimal_os", "confidence", "notes"]
    with out.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(INIT_ROWS)


def write_md(out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    md = [
        "# Spark Init State",
        "",
        "## Purpose",
        "",
        "Document the initialization and crank-to-run seeding required before `LA906` can safely command spark through the ASIC handoff path.",
        "",
        "This contract is about first-event validity. It does **not** create a spark handoff stub.",
        "",
        "## Scope",
        "",
        "This contract covers the state required before the first valid run-mode spark handoff:",
        "",
        "- `$3FF6`",
        "- `$3FDC`",
        "- `$01EC`",
        "- `$3FE4/$3FEC`",
        "- `$3FE8/$3FE6`",
        "- `L005F/L0060`",
        "- `$3FC0`",
        "- run/bypass flags that gate the first `LA906` call",
        "",
        "## Current Model",
        "",
        "`LA906` requires rolling timing state. Therefore the minimal OS must either:",
        "",
        "1. reproduce the stock seed/init sequence, or",
        "2. define an equivalent safe seed from current REF/DRP period and desired spark.",
        "",
        "## Static Init Rows",
        "",
        "| PC | Target | Access | Context | Candidate role | Required? | Confidence |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in INIT_ROWS:
        target = f"{r['state_symbol']} ({r['state_address']})"
        access = f"{r['mnemonic']} {r['operands']}".strip()
        md.append(f"| `{r['pc']}` | {target} | `{access}` | {r['init_context']} | {r['candidate_role']} | {r['required_for_minimal_os']} | {r['confidence']} |")
    md += [
        "",
        "## Crank-to-Run Transition",
        "",
        "Static evidence currently supports this conservative transition model:",
        "",
        "```text",
        "1. key-on/reset global ASIC clear seeds $3FC0-$3FF8 even words to $0000",
        "2. REF/DRP period capture becomes available through $3FC0",
        "3. software period basis L005F/L0060 is seeded from $3FC0 or derived period/RPM fallback",
        "4. timing work term L01EC is seeded/refined before LA906 uses it",
        "5. sign flag L004F bit0 is initialized per conversion event",
        "6. first LA906 run update consumes existing $3FF6/$3FDC",
        "7. first LA906 run update then seeds $3FDC/$3FF6 for subsequent events",
        "8. $3FEC->$3FE4 mirror may acknowledge or synchronize first valid output state",
        "```",
        "",
        "The unresolved risk is step 6: if global-clear zero is not a valid first seed for `$3FF6/$3FDC`, stock code must have a separate first-event seed or must avoid LA906 until the rolling state is valid.",
        "",
        "## State-Specific Interpretation",
        "",
        "### `$3FF6/$3FF7`",
        "",
        "No non-LA906 seed has been locked yet beyond the global ASIC clear. The first LA906 read of `$3FF6` therefore creates the key first-event question: is `$0000` a safe seed, or does a bypass/run gate delay LA906 until hardware/stock state has populated it?",
        "",
        "### `$3FDC/$3FDD`",
        "",
        "`$3FDC` is globally cleared, then first consumed by `ADDD L3FDC` before being updated from `L01EC`. This means the first run event must either tolerate `$3FDC=$0000` or execute a separate seed path before the read.",
        "",
        "### `L01EC/L01ED`",
        "",
        "`L01EC` has pre-LA906 writers around `0xA6EC-$0xA6FD`. It is the strongest explicit software seed candidate for the rolling-state model because it is later subtracted before `$3FE6` and copied into `$3FDC`.",
        "",
        "### `L005F/L0060` and `$3FC0`",
        "",
        "The period basis must be valid before the conversion equation can generate a sane `D_AB97`. If no valid REF/DRP period exists, the minimal OS must hold spark in safe/bypass/default behavior.",
        "",
        "### `$3FEC -> $3FE4`",
        "",
        "The mirror/ack sequence occurs after the paired timing writes. Until bench testing says otherwise, treat it as part of first-event synchronization, not optional decoration.",
        "",
        "## Required New-OS Behavior",
        "",
        "The future minimal spark module must provide:",
        "",
        "1. safe default spark state at key-on",
        "2. valid period basis before first run spark",
        "3. valid rolling anchor before first `$3FE8/$3FE6` write",
        "4. valid prior-edge/paired-edge state before first `$3FDC` use",
        "5. bypass-to-EST transition behavior that does not produce a wild spark event",
        "6. safe behavior if REF/DRP period is missing or invalid",
        "",
        "## Current Static Classification",
        "",
        "```text",
        "INIT-A:",
        "  not proven. Static rows show period/L01EC seeds, but no locked explicit $3FF6/$3FDC seed before first LA906 beyond global clear.",
        "",
        "INIT-B:",
        "  plausible. $3FF6/$3FDC may only become fully meaningful after one LA906 iteration.",
        "",
        "INIT-C:",
        "  plausible and important. Startup/bypass may avoid ASIC spark handoff until rolling state is valid.",
        "",
        "INIT-D:",
        "  plausible. $3FEC->$3FE4 may acknowledge or synchronize first valid state.",
        "",
        "INIT-E:",
        "  possible until crank-to-run trace is captured.",
        "```",
        "",
        "## Minimal-OS Expected Split",
        "",
        "```text",
        "SPARK_INIT_STATE:",
        "  clear/default output state",
        "  wait for valid REF/DRP period",
        "  seed $3FF6/$3FDC/L01EC from period/capture or safe defaults",
        "  permit LA906-style handoff only when valid",
        "",
        "SPARK_CONVERT:",
        "  degrees → D_AB97",
        "",
        "SPARK_ROLLING_UPDATE:",
        "  maintain $3FF6/$3FDC",
        "",
        "SPARK_ASIC_HANDOFF:",
        "  write $3FE8/$3FE6",
        "  mirror $3FEC->$3FE4 if required",
        "```",
        "",
        "## Next Contract",
        "",
        "If this pass does not fully capture bypass/EST transition behavior, next target:",
        "",
        "```text",
        "SPARK_BYPASS_EST_TRANSITION.md",
        "```",
    ]
    out.write_text("\n".join(md), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", default="source/31/BMHM_HAC_ORG_7100_to_end.asm")
    ap.add_argument("--map", default="maps/full/hardware_access_map_v0.3.csv")
    ap.add_argument("--rolling", default="maps/contracts/spark_rolling_state_model.csv")
    ap.add_argument("--la906", default="maps/contracts/spark_la906_output_sequence.csv")
    ap.add_argument("--out-md", required=True)
    ap.add_argument("--out-csv", required=True)
    args = ap.parse_args()

    for dep in [args.source, args.rolling, args.la906]:
        touch_required(dep)
    write_csv(resolve_path(args.out_csv))
    write_md(resolve_path(args.out_md))
    print(f"spark init rows: {len(INIT_ROWS)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
