#!/usr/bin/env python3
"""Build the Spark EST fault-monitor contract.

This pass isolates the Error 42 / EST monitor path from spark authority and
LA906 timing math. It does not create a spark writer or module boundary.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

ROWS = [
    {
        "stage": "monitor_enable_precheck",
        "pc": "0xA51B",
        "mnemonic": "BRCLR",
        "operands": "L004F,#$40,LA57F",
        "symbol": "L004F bit6",
        "address": "0x004F",
        "read_or_write": "read_bit",
        "bitmask": "0x40",
        "value_source": "major-loop EST monitor enable flag",
        "routine_label": "LA51B",
        "monitor_context": "pre-run/spark path monitor gate",
        "candidate_role": "est_monitor_enable",
        "enable_condition": "set on previous good EST monitor path at 0xAC1C",
        "fault_condition": "monitor skipped if clear",
        "clear_condition": "not shown in this row",
        "side_effect_candidate": "monitor gate, not proven physical EST authority",
        "required_for_minimal_os": "only_if_stock_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "L004F bit6 gates monitor logic; not proven as physical bypass/EST output control",
    },
    {
        "stage": "engine_running_context",
        "pc": "0xA510/0xA56E",
        "mnemonic": "BRCLR/BSET",
        "operands": "L004F,#$80",
        "symbol": "L004F bit7",
        "address": "0x004F",
        "read_or_write": "read_then_write_bit",
        "bitmask": "0x80",
        "value_source": "run qualification result",
        "routine_label": "LA50A/LA56E",
        "monitor_context": "run qualification context",
        "candidate_role": "engine_running_gate",
        "enable_condition": "RPM threshold plus DRP/ref event count gates pass",
        "fault_condition": "monitor should not matter before run qualification",
        "clear_condition": "cleared during reset/stall cleanup at 0x7D78",
        "side_effect_candidate": "run-state authority gate",
        "required_for_minimal_os": "yes_for_run_qualification",
        "confidence": "high_static",
        "notes": "engine-running bit is context for when EST monitor should become relevant",
    },
    {
        "stage": "first_drp_gate",
        "pc": "0xABCB",
        "mnemonic": "BRCLR",
        "operands": "L0044,#$08,LAC31",
        "symbol": "L0044 bit3",
        "address": "0x0044",
        "read_or_write": "read_bit",
        "bitmask": "0x08",
        "value_source": "first DRP valid latch",
        "routine_label": "LABA2",
        "monitor_context": "post-LA906 EST monitor gate",
        "candidate_role": "first_drp_gate",
        "enable_condition": "first DRP valid latch set",
        "fault_condition": "monitor skipped if no first DRP valid",
        "clear_condition": "cleared after monitor/event consumption at 0xAC25",
        "side_effect_candidate": "event-gating for monitor, possible first-event safety",
        "required_for_minimal_os": "yes_if_stock_monitor_retained",
        "confidence": "high_static",
        "notes": "monitor check is gated by first DRP valid after LA906 path",
    },
    {
        "stage": "recent_drp_gate",
        "pc": "0xABCF",
        "mnemonic": "BRCLR",
        "operands": "L0050,#$04,LAC10",
        "symbol": "L0050 bit2",
        "address": "0x0050",
        "read_or_write": "read_bit",
        "bitmask": "0x04",
        "value_source": "DRP occurred 6.25 ms test flag",
        "routine_label": "LABA2",
        "monitor_context": "post-LA906 EST monitor gate",
        "candidate_role": "recent_drp_gate",
        "enable_condition": "recent DRP occurred flag set",
        "fault_condition": "monitor skipped if no recent DRP",
        "clear_condition": "not resolved in this contract",
        "side_effect_candidate": "prevents false EST fault during missing-ref/dropout",
        "required_for_minimal_os": "yes_if_stock_monitor_retained_or_equivalent_dropout_gate_needed",
        "confidence": "medium_high_static",
        "notes": "source comment: DRP OCCURRED 6.25msec TEST",
    },
    {
        "stage": "captured_ref_current_read",
        "pc": "0xABD3",
        "mnemonic": "LDD",
        "operands": "L3FCA",
        "symbol": "L3FCA",
        "address": "0x3FCA",
        "read_or_write": "read",
        "bitmask": "",
        "value_source": "ASIC/RPM/ref count source",
        "routine_label": "LABA2",
        "monitor_context": "Error 42 A monitor sample",
        "candidate_role": "captured_ref_current",
        "enable_condition": "first DRP valid and recent DRP gates pass",
        "fault_condition": "current sample compared against L0205 prior sample",
        "clear_condition": "good path stores new sample",
        "side_effect_candidate": "fault monitor sample source, not direct authority output",
        "required_for_minimal_os": "only_if_stock_fault_monitor_retained",
        "confidence": "medium_static",
        "notes": "current EST/ref monitor sample source",
    },
    {
        "stage": "captured_ref_previous_compare",
        "pc": "0xABEA",
        "mnemonic": "SUBD",
        "operands": "L0205",
        "symbol": "L0205",
        "address": "0x0205",
        "read_or_write": "read",
        "bitmask": "",
        "value_source": "prior stored L3FCA sample",
        "routine_label": "LABA2",
        "monitor_context": "Error 42 A delta check",
        "candidate_role": "captured_ref_previous",
        "enable_condition": "current L3FCA sample available",
        "fault_condition": "no/invalid delta candidate increments counter path",
        "clear_condition": "new sample stored at 0xAC0D",
        "side_effect_candidate": "fault monitor comparison only, side effects pending",
        "required_for_minimal_os": "only_if_stock_fault_monitor_retained",
        "confidence": "medium_static",
        "notes": "corrected monitor pair uses L0205, not L0204, in captured rows",
    },
    {
        "stage": "err42_mask_gate",
        "pc": "0xABDD",
        "mnemonic": "BRCLR",
        "operands": "0,Y,#$20,LAC1C",
        "symbol": "ERR word 4 bit5",
        "address": "0x5B03 bit5 candidate",
        "read_or_write": "read_bit",
        "bitmask": "0x20",
        "value_source": "error mask/status word",
        "routine_label": "LABA2",
        "monitor_context": "Error 42 A enabled/disabled path",
        "candidate_role": "est_fault_threshold",
        "enable_condition": "ERR 42 monitor/error bit enabled",
        "fault_condition": "if enabled, monitor may increment counter",
        "clear_condition": "good path branches to LAC1C",
        "side_effect_candidate": "diagnostic/error reporting gate",
        "required_for_minimal_os": "no_if_monitor_omitted_or_disabled",
        "confidence": "medium_static",
        "notes": "source comment references ERR 42, EST MONITOR ERROR",
    },
    {
        "stage": "monitor_enabled_shortcut",
        "pc": "0xABE2",
        "mnemonic": "BRSET",
        "operands": "L004F,#$40,LAC25",
        "symbol": "L004F bit6",
        "address": "0x004F",
        "read_or_write": "read_bit",
        "bitmask": "0x40",
        "value_source": "major-loop EST monitor enable flag",
        "routine_label": "LABA2",
        "monitor_context": "Error 42 A monitor path",
        "candidate_role": "est_monitor_enable",
        "enable_condition": "if already enabled, branch to event consume/mirror path",
        "fault_condition": "skips initial-good path setup when set",
        "clear_condition": "not shown in this row",
        "side_effect_candidate": "monitor-state control, not proven spark-authority control",
        "required_for_minimal_os": "only_if_stock_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "bit6 controls monitor state flow inside EST check path",
    },
    {
        "stage": "est_error_counter_increment",
        "pc": "0xAC06/0xAC07",
        "mnemonic": "INCB/STAB",
        "operands": "L022C",
        "symbol": "L022C",
        "address": "0x022C",
        "read_or_write": "read_modify_write/write",
        "bitmask": "",
        "value_source": "incremented EST ERR counter",
        "routine_label": "LABFE",
        "monitor_context": "Error 42 A fault accumulation",
        "candidate_role": "est_fault_counter",
        "enable_condition": "monitor gates pass and fault path taken",
        "fault_condition": "counter increments toward L4E72 threshold",
        "clear_condition": "cleared on good path at 0xAC1F",
        "side_effect_candidate": "diagnostic counter; authority side effect not proven",
        "required_for_minimal_os": "no_if_MON_A; yes_if_MON_B_or_MON_C",
        "confidence": "high_static",
        "notes": "source comments identify EST ERR CNTR; threshold L4E72=4 NUM EST ERR'S FR 42A",
    },
    {
        "stage": "first_good_flag_clear_on_fault_path",
        "pc": "0xAC0A",
        "mnemonic": "BCLR",
        "operands": "L0044,#$40",
        "symbol": "L0044 bit6",
        "address": "0x0044",
        "read_or_write": "write_bit",
        "bitmask": "0x40",
        "value_source": "fault/not-good path",
        "routine_label": "LABFE",
        "monitor_context": "Error 42 A fault accumulation",
        "candidate_role": "est_fault_set",
        "enable_condition": "fault path after counter increment",
        "fault_condition": "clears first-good ERR42A flag candidate",
        "clear_condition": "good monitor path may set/maintain related state elsewhere",
        "side_effect_candidate": "diagnostic state; authority side effect unknown",
        "required_for_minimal_os": "no_if_monitor_omitted_or_disabled",
        "confidence": "medium_static",
        "notes": "source comment: CLR b6, 1st GOOD ERR 42A FLAG",
    },
    {
        "stage": "captured_ref_previous_store",
        "pc": "0xAC0D",
        "mnemonic": "STX",
        "operands": "L0205",
        "symbol": "L0205",
        "address": "0x0205",
        "read_or_write": "write",
        "bitmask": "",
        "value_source": "X=current L3FCA sample",
        "routine_label": "LAC0D",
        "monitor_context": "Error 42 A sample update",
        "candidate_role": "captured_ref_previous",
        "enable_condition": "monitor path reached sample-store point",
        "fault_condition": "next cycle compares against this value",
        "clear_condition": "overwritten every valid sample-store event",
        "side_effect_candidate": "monitor-only memory state",
        "required_for_minimal_os": "only_if_stock_fault_monitor_retained",
        "confidence": "medium_static",
        "notes": "stores current sample as next prior sample",
    },
    {
        "stage": "locked_err42a_set",
        "pc": "0xAC13",
        "mnemonic": "BSET",
        "operands": "L0044,#$80",
        "symbol": "L0044 bit7",
        "address": "0x0044",
        "read_or_write": "write_bit",
        "bitmask": "0x80",
        "value_source": "EST error threshold path",
        "routine_label": "LAC13",
        "monitor_context": "Error 42 A threshold reached",
        "candidate_role": "est_fault_threshold",
        "enable_condition": "L022C exceeds/equals L4E72 threshold candidate",
        "fault_condition": "locks ERR42A state candidate",
        "clear_condition": "not resolved in this contract",
        "side_effect_candidate": "diagnostic/fault-latch; bypass/fuel side effect not proven",
        "required_for_minimal_os": "no_if_MON_A; yes_if_monitor_retained",
        "confidence": "medium_high_static",
        "notes": "source comment indicates LOCKED IN ERR 42A; comment bit number mismatch possible",
    },
    {
        "stage": "monitor_enable_set_good_path",
        "pc": "0xAC1C",
        "mnemonic": "BSET",
        "operands": "L004F,#$40",
        "symbol": "L004F bit6",
        "address": "0x004F",
        "read_or_write": "write_bit",
        "bitmask": "0x40",
        "value_source": "good EST monitor path",
        "routine_label": "LAC1C",
        "monitor_context": "Error 42 A good path",
        "candidate_role": "est_monitor_enable",
        "enable_condition": "good EST monitor check path",
        "fault_condition": "not fault path",
        "clear_condition": "not shown; bit6 is tested elsewhere",
        "side_effect_candidate": "enables future monitor checks; physical authority not proven",
        "required_for_minimal_os": "only_if_stock_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "source comment: SET b6, MAJOR LOOP EST MONITOR ENABLE",
    },
    {
        "stage": "est_error_counter_clear",
        "pc": "0xAC1F",
        "mnemonic": "CLR",
        "operands": "L022C",
        "symbol": "L022C",
        "address": "0x022C",
        "read_or_write": "write",
        "bitmask": "",
        "value_source": "good EST monitor path",
        "routine_label": "LAC1C",
        "monitor_context": "Error 42 A recovery/good path",
        "candidate_role": "est_fault_clear",
        "enable_condition": "good monitor path",
        "fault_condition": "clears accumulated counter",
        "clear_condition": "CLR L022C",
        "side_effect_candidate": "diagnostic counter recovery; authority side effect not proven",
        "required_for_minimal_os": "only_if_stock_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "clears EST error counter after good path",
    },
    {
        "stage": "event_latch_clear_after_monitor",
        "pc": "0xAC25",
        "mnemonic": "BCLR",
        "operands": "L0044,#$08",
        "symbol": "L0044 bit3",
        "address": "0x0044",
        "read_or_write": "write_bit",
        "bitmask": "0x08",
        "value_source": "post-monitor event consumed",
        "routine_label": "LAC25",
        "monitor_context": "post-monitor event rearm",
        "candidate_role": "first_drp_gate",
        "enable_condition": "monitor/event path reached completion",
        "fault_condition": "not direct fault path",
        "clear_condition": "clears first DRP valid latch for next event",
        "side_effect_candidate": "event rearm; may protect first-event monitor behavior",
        "required_for_minimal_os": "yes_if_stock_event_latch_retained",
        "confidence": "high_static",
        "notes": "event-consumption step shared with mirror path",
    },
    {
        "stage": "asic_status_mirror_read",
        "pc": "0xAC28",
        "mnemonic": "LDX",
        "operands": "L3FEC",
        "symbol": "L3FEC",
        "address": "0x3FEC",
        "read_or_write": "read",
        "bitmask": "",
        "value_source": "ASIC status/source/capture",
        "routine_label": "LAC25",
        "monitor_context": "post-monitor ASIC status/mirror",
        "candidate_role": "asic_status_mirror",
        "enable_condition": "event/monitor path reaches LAC25",
        "fault_condition": "may affect monitor or handoff if skipped",
        "clear_condition": "mirror write follows at 0xAC2E",
        "side_effect_candidate": "shared ACK/status sync candidate",
        "required_for_minimal_os": "likely_yes_until_bench_disproves_if_LA906_path_retained",
        "confidence": "medium_static",
        "notes": "same mirror path as LA906 output sequence; could belong to monitor, handoff ACK, or both",
    },
    {
        "stage": "asic_status_mirror_write",
        "pc": "0xAC2E",
        "mnemonic": "STX",
        "operands": "L3FE4",
        "symbol": "L3FE4",
        "address": "0x3FE4",
        "read_or_write": "write",
        "bitmask": "",
        "value_source": "X=$3FEC",
        "routine_label": "LAC25",
        "monitor_context": "post-monitor ASIC status/mirror",
        "candidate_role": "asic_status_mirror",
        "enable_condition": "L3FEC read occurred",
        "fault_condition": "skipping may reveal ACK/monitor side effect",
        "clear_condition": "not a clear; mirror/ack candidate",
        "side_effect_candidate": "shared ACK/status sync candidate",
        "required_for_minimal_os": "likely_yes_until_bench_disproves_if_LA906_path_retained",
        "confidence": "medium_static",
        "notes": "write side of $3FEC->$3FE4 mirror",
    },
    {
        "stage": "major_loop_monitor_gate",
        "pc": "0xE019",
        "mnemonic": "BRCLR",
        "operands": "L004F,#$40,LE041",
        "symbol": "L004F bit6",
        "address": "0x004F",
        "read_or_write": "read_bit",
        "bitmask": "0x40",
        "value_source": "major-loop EST monitor enable flag",
        "routine_label": "LE011",
        "monitor_context": "Error 42 B / major-loop monitor",
        "candidate_role": "est_monitor_enable",
        "enable_condition": "bit6 set by good path",
        "fault_condition": "major-loop monitor skipped if clear",
        "clear_condition": "not shown in this row",
        "side_effect_candidate": "diagnostic monitor gate",
        "required_for_minimal_os": "only_if_stock_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "second monitor site confirms bit6 as monitor enable",
    },
    {
        "stage": "major_loop_rpm_fault_gate",
        "pc": "0xE023",
        "mnemonic": "CMPA",
        "operands": "L4E70",
        "symbol": "L4E70",
        "address": "0x4E70",
        "read_or_write": "read_cal_compare",
        "bitmask": "",
        "value_source": "A=RPM/25",
        "routine_label": "LE011",
        "monitor_context": "Error 42 B / major-loop RPM gate",
        "candidate_role": "rpm_threshold_gate",
        "enable_condition": "RPM above L4E70 threshold",
        "fault_condition": "ERR 42 monitor active above RPM threshold",
        "clear_condition": "not shown in this row",
        "side_effect_candidate": "diagnostic monitor RPM gate",
        "required_for_minimal_os": "only_if_stock_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "source comment: RPM LIMIT, 450 RPM, ERR 42",
    },
]

FIELDS = [
    "stage", "pc", "mnemonic", "operands", "symbol", "address", "read_or_write",
    "bitmask", "value_source", "routine_label", "monitor_context", "candidate_role",
    "enable_condition", "fault_condition", "clear_condition", "side_effect_candidate",
    "required_for_minimal_os", "confidence", "notes",
]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def resolve(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else repo_root() / p


def require(path: str | Path) -> None:
    p = resolve(path)
    if not p.exists():
        raise FileNotFoundError(p)


def write_csv(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(ROWS)


def write_md(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Spark EST Fault Monitor Contract",
        "",
        "## Purpose",
        "",
        "Classify the EST/Error 42 monitor path and determine whether it is required for minimal spark authority or only diagnostic behavior.",
        "",
        "This contract does not create a spark writer and does not define the final minimal module boundary.",
        "",
        "## Current Static Context",
        "",
        "The bypass/EST transition pass found:",
        "",
        "```text",
        "L004F bit7 = engine-running flag",
        "L0044 bit3 = first DRP valid latch",
        "L4133 = 450 RPM bypass-to-run threshold candidate",
        "L0210 = qualifying DRP/ref event counter",
        "L004F bit6 = EST monitor enable",
        "L3FCA -> L0205 -> L022C = captured Error 42 monitor path",
        "$3FEC -> $3FE4 = possible status/mirror/ack",
        "```",
        "",
        "## Core Question",
        "",
        "Can the minimal OS safely keep EST monitor disabled or simplified while still allowing EST authority and LA906 spark handoff?",
        "",
        "## Monitor Path Summary",
        "",
        "| Symbol | Candidate role | Evidence | Confidence |",
        "|---|---|---|---|",
        "| `L004F bit6` | EST monitor enable | tested at `0xA51B` and `0xE019`, set at `0xAC1C` | high_static |",
        "| `L004F bit7` | engine-running context | tested/set by run qualification | high_static |",
        "| `L0044 bit3` | first DRP valid gate | tested at `0xABCB`, cleared at `0xAC25` | high_static |",
        "| `L0050 bit2` | recent DRP gate | tested at `0xABCF` | medium_high_static |",
        "| `L3FCA` | current captured/ref sample | read at `0xABD3` | medium_static |",
        "| `L0205` | prior captured/ref sample | read at `0xABEA`, written at `0xAC0D` | medium_static |",
        "| `L022C` | EST error counter | incremented at `0xAC06/0xAC07`, cleared at `0xAC1F` | high_static |",
        "| `L0044 bit7` | locked ERR42A candidate | set at `0xAC13` | medium_high_static |",
        "| `$3FEC->$3FE4` | status/mirror/ack candidate | read/write at `0xAC28/0xAC2E` | medium_static |",
        "",
        "## Static Monitor Rows",
        "",
        "| Stage | PC | Instruction | Symbol | Role | Required? | Confidence |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in ROWS:
        inst = f"{r['mnemonic']} {r['operands']}".strip()
        lines.append(f"| {r['stage']} | `{r['pc']}` | `{inst}` | `{r['symbol']}` | {r['candidate_role']} | {r['required_for_minimal_os']} | {r['confidence']} |")
    lines += [
        "",
        "## Static Fault-Monitor Model",
        "",
        "```text",
        "enable/gating:",
        "  L004F bit6 is the monitor-enable state.",
        "  L0044 bit3 first-DRP-valid and L0050 bit2 recent-DRP gates prevent false checks.",
        "  Major-loop monitor also gates on L004F bit6 and RPM threshold L4E70.",
        "",
        "sample/delta:",
        "  current hardware/ref sample comes from L3FCA.",
        "  prior sample is stored in L0205.",
        "  monitor compares or differences L3FCA against L0205.",
        "",
        "fault accumulation:",
        "  L022C is the captured EST error counter.",
        "  L4E72 is the threshold candidate: 4 EST errors for 42A.",
        "  threshold path sets a locked ERR42A candidate bit in L0044.",
        "",
        "good/recovery path:",
        "  good path sets L004F bit6 monitor enable.",
        "  good path clears L022C.",
        "  current L3FCA sample is stored to L0205 for next comparison.",
        "",
        "shared mirror path:",
        "  L3FEC is read and mirrored to L3FE4 after event/monitor path completion.",
        "```",
        "",
        "## Required Answers",
        "",
        "- What enables EST monitoring?",
        "- What disables it?",
        "- What increments `L022C`?",
        "- What clears `L022C`?",
        "- What threshold sets Error 42?",
        "- Does Error 42 force bypass/module timing?",
        "- Does Error 42 inhibit `LA906`?",
        "- Does Error 42 change spark command, fuel, or limp behavior?",
        "- Does `$3FEC->$3FE4` belong to the monitor, handoff ACK, or both?",
        "- Can a minimal OS safely omit the monitor?",
        "- Can a minimal OS keep monitor disabled without side effects?",
        "",
        "## Current Static Answers",
        "",
        "```text",
        "monitor enable:",
        "  L004F bit6 is clearly a monitor-enable/control flag.",
        "",
        "monitor fault condition:",
        "  captured static path compares current L3FCA behavior against stored L0205 behavior and increments L022C on fault path.",
        "",
        "counter clear:",
        "  good path clears L022C at 0xAC1F.",
        "",
        "fault threshold:",
        "  L4E72 is the static threshold candidate with source comment indicating 4 EST errors for 42A.",
        "",
        "authority side effect:",
        "  not proven. Static rows show monitor/error state, but no locked direct write that forces bypass or disables LA906 in this contract.",
        "",
        "fuel/run side effect:",
        "  not proven in this pass.",
        "",
        "mirror path:",
        "  $3FEC->$3FE4 remains shared/ambiguous: monitor completion, handoff ACK, status sync, or all three.",
        "```",
        "",
        "## Minimal-OS Impact",
        "",
        "If MON-A is bench-proven, the minimal OS can omit or keep the EST monitor disabled while still implementing safe run qualification, bypass/EST authority, LA906 conversion, rolling state, and ASIC handoff.",
        "",
        "If MON-B/MON-C/MON-D is bench-proven, the monitor or parts of it become required hardware-contract behavior and must be represented in the minimal module boundary.",
        "",
        "## Classification",
        "",
        "```text",
        "MON-A:",
        "  possible. Static evidence has not proven a direct authority/fuel side effect.",
        "",
        "MON-B:",
        "  not proven. L004F bit6 gates the monitor, but is not yet proven to gate physical spark authority.",
        "",
        "MON-C:",
        "  possible after fault threshold, but no direct fallback/bypass side effect is locked yet.",
        "",
        "MON-D:",
        "  plausible. $3FEC->$3FE4 is shared with the LA906 post-event path and cannot be omitted until bench disproves it.",
        "",
        "MON-E:",
        "  possible until fault-threshold and bypass-wire behavior are bench-classified.",
        "```",
        "",
        "## Next Contract",
        "",
        "After this pass, the next non-code artifact should be:",
        "",
        "```text",
        "SPARK_MINIMAL_MODULE_BOUNDARY.md",
        "```",
        "",
        "No `SPARK_WRITE` or spark handoff stub until the module boundary is written and the bench gates are explicit.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default="source/31/BMHM_HAC_ORG_7100_to_end.asm")
    parser.add_argument("--map", default="maps/full/hardware_access_map_v0.2.csv")
    parser.add_argument("--name", default="SPARK_EST_FAULT_MONITOR")
    parser.add_argument("--watch", action="append", default=[])
    parser.add_argument("--out-md", required=True)
    parser.add_argument("--out-csv", required=True)
    args = parser.parse_args()

    require(args.source)
    require(args.map)
    write_csv(resolve(args.out_csv))
    write_md(resolve(args.out_md))
    print(f"{args.name}: wrote {len(ROWS)} monitor rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
