#!/usr/bin/env python3
"""Build the spark BYPASS / EST transition contract.

This pass documents authority transfer from module/base timing to PCM/ASIC EST
control. It uses the committed v0.2 hardware access map by default and does not
create any spark writer or handoff stub.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

ROWS = [
    {
        "stage": "safe_default_engine_running_clear",
        "pc": "0x7D78",
        "mnemonic": "BCLR",
        "operands": "L004F,#$80",
        "symbol": "L004F bit7",
        "address": "0x004F",
        "read_or_write": "write_bit",
        "bitmask": "0x80",
        "value_source": "clear engine-running flag",
        "routine_label": "L7D4B reset/stall cleanup",
        "transition_context": "key_on_or_stall_safe_default",
        "candidate_role": "engine_running",
        "bypass_state": "safe/default bypass authority",
        "est_state": "not_authorized",
        "run_state": "not_running",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "source comment: CLR b7, ENGINE RUNNING",
    },
    {
        "stage": "safe_default_run_fuel_clear",
        "pc": "0x7D7B",
        "mnemonic": "BCLR",
        "operands": "L004F,#$10",
        "symbol": "L004F bit4",
        "address": "0x004F",
        "read_or_write": "write_bit",
        "bitmask": "0x10",
        "value_source": "clear run-fuel flag",
        "routine_label": "L7D4B reset/stall cleanup",
        "transition_context": "key_on_or_stall_safe_default",
        "candidate_role": "run_qualification",
        "bypass_state": "safe/default bypass authority",
        "est_state": "not_authorized",
        "run_state": "not_run_fuel",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "source comment: CLR b4, RUN FUEL",
    },
    {
        "stage": "first_drp_valid_clear_on_startup_window",
        "pc": "0x7D9A",
        "mnemonic": "BCLR",
        "operands": "L0044,#$08",
        "symbol": "L0044 bit3",
        "address": "0x0044",
        "read_or_write": "write_bit",
        "bitmask": "0x08",
        "value_source": "clear first DRP valid latch",
        "routine_label": "L7D90 startup/restart branch",
        "transition_context": "startup_or_restart_rearm",
        "candidate_role": "drp_count_gate",
        "bypass_state": "bypass until first DRP revalidated",
        "est_state": "not_authorized_until_revalidated",
        "run_state": "not_yet_qualified",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "clears 1st DRP VALID during startup/restart rearm path",
    },
    {
        "stage": "run_gate_engine_running_test",
        "pc": "0xA510",
        "mnemonic": "BRCLR",
        "operands": "L004F,#$80,LA540",
        "symbol": "L004F bit7",
        "address": "0x004F",
        "read_or_write": "read_bit",
        "bitmask": "0x80",
        "value_source": "engine-running flag",
        "routine_label": "LA50A spark/run qualification front gate",
        "transition_context": "before_spark_run_path",
        "candidate_role": "engine_running",
        "bypass_state": "if clear go qualify crank/run",
        "est_state": "gated by run qualification",
        "run_state": "engine-running candidate",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "branches to LA540 if engine-running bit is clear",
    },
    {
        "stage": "run_gate_run_fuel_test",
        "pc": "0xA514",
        "mnemonic": "BRSET",
        "operands": "L004F,#$10,LA51B",
        "symbol": "L004F bit4",
        "address": "0x004F",
        "read_or_write": "read_bit",
        "bitmask": "0x10",
        "value_source": "run-fuel flag",
        "routine_label": "LA50A spark/run qualification front gate",
        "transition_context": "before_spark_run_path",
        "candidate_role": "run_qualification",
        "bypass_state": "startup filter if clear",
        "est_state": "run path if set",
        "run_state": "run-fuel candidate",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "yes",
        "confidence": "medium_high_static",
        "notes": "source comment: BR IF b4, RUN FUEL",
    },
    {
        "stage": "first_drp_valid_test",
        "pc": "0xA540",
        "mnemonic": "BRSET",
        "operands": "L0044,#$08,LA54A",
        "symbol": "L0044 bit3",
        "address": "0x0044",
        "read_or_write": "read_bit",
        "bitmask": "0x08",
        "value_source": "first DRP valid latch",
        "routine_label": "LA540 run qualification",
        "transition_context": "first_ref_event_gate",
        "candidate_role": "drp_count_gate",
        "bypass_state": "bypass/startup until first DRP valid",
        "est_state": "not_authorized until first DRP valid",
        "run_state": "first DRP valid candidate",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "source comment: BR IF b3, 1st DRP VALID",
    },
    {
        "stage": "first_drp_valid_set",
        "pc": "0xA544",
        "mnemonic": "BSET",
        "operands": "L0044,#$08",
        "symbol": "L0044 bit3",
        "address": "0x0044",
        "read_or_write": "write_bit",
        "bitmask": "0x08",
        "value_source": "first accepted DRP/ref event",
        "routine_label": "LA540 run qualification",
        "transition_context": "first_ref_event_gate",
        "candidate_role": "drp_count_gate",
        "bypass_state": "first DRP latched; still not fully run-qualified",
        "est_state": "not_authorized this event",
        "run_state": "first_drp_seen",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "source comment: SET b3, 1st DRP VALID",
    },
    {
        "stage": "rpm_threshold_compare",
        "pc": "0xA554",
        "mnemonic": "CPD",
        "operands": "L4133",
        "symbol": "L4133",
        "address": "0x4133",
        "read_or_write": "read_cal_compare",
        "bitmask": "",
        "value_source": "D from L3FC0 period/counter path",
        "routine_label": "LA551 run qualification",
        "transition_context": "rpm_threshold_gate",
        "candidate_role": "rpm_threshold_gate",
        "bypass_state": "bypass until threshold met",
        "est_state": "not_authorized until run-qualified",
        "run_state": "450 RPM threshold candidate",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "source comment: 450 RPM BYPASS TO RUN ENABLE IN REF PERIOD",
    },
    {
        "stage": "run_event_counter_increment",
        "pc": "0xA560",
        "mnemonic": "INC",
        "operands": "L0210",
        "symbol": "L0210",
        "address": "0x0210",
        "read_or_write": "rmw",
        "bitmask": "",
        "value_source": "qualifying DRP/ref event",
        "routine_label": "LA560 run qualification",
        "transition_context": "run_event_count_gate",
        "candidate_role": "drp_count_gate",
        "bypass_state": "bypass until count satisfied",
        "est_state": "not_authorized until count satisfied",
        "run_state": "qualifying count increments",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "yes",
        "confidence": "medium_high_static",
        "notes": "run qualification counter increments after RPM threshold path",
    },
    {
        "stage": "run_event_counter_threshold",
        "pc": "0xA566",
        "mnemonic": "CMPA",
        "operands": "L4142",
        "symbol": "L4142",
        "address": "0x4142",
        "read_or_write": "read_cal_compare",
        "bitmask": "",
        "value_source": "A=L0210 qualifying event counter",
        "routine_label": "LA560 run qualification",
        "transition_context": "run_event_count_gate",
        "candidate_role": "drp_count_gate",
        "bypass_state": "bypass until count satisfied",
        "est_state": "not_authorized until count satisfied",
        "run_state": "DRP/ref count threshold candidate",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "source comment: NUM CNT'S SPK RUN FLAG SET IF RPM GT 2 DRP'S",
    },
    {
        "stage": "engine_running_set",
        "pc": "0xA56E",
        "mnemonic": "BSET",
        "operands": "L004F,#$80",
        "symbol": "L004F bit7",
        "address": "0x004F",
        "read_or_write": "write_bit",
        "bitmask": "0x80",
        "value_source": "RPM threshold plus DRP/ref count qualification",
        "routine_label": "LA56E run qualified",
        "transition_context": "spark_authority_transfer_candidate",
        "candidate_role": "engine_running",
        "bypass_state": "transition candidate",
        "est_state": "run/EST authority candidate",
        "run_state": "engine_running_set",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "source comment: SET b7, ENGINE RUNNING",
    },
    {
        "stage": "startup_spark_override_clear",
        "pc": "0xA57C",
        "mnemonic": "STD",
        "operands": "L01F2",
        "symbol": "L01F2",
        "address": "0x01F2",
        "read_or_write": "write",
        "bitmask": "",
        "value_source": "D=$0000",
        "routine_label": "LA56E run qualified",
        "transition_context": "leaving_startup_spark",
        "candidate_role": "spark_authority_transfer",
        "bypass_state": "leaving startup mode",
        "est_state": "run/EST authority candidate",
        "run_state": "startup spark cleared",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "likely_yes_if_startup_override_retained",
        "confidence": "medium_static",
        "notes": "clears START UP SPARK after engine-running qualification",
    },
    {
        "stage": "est_monitor_enable_test",
        "pc": "0xA51B",
        "mnemonic": "BRCLR",
        "operands": "L004F,#$40,LA57F",
        "symbol": "L004F bit6",
        "address": "0x004F",
        "read_or_write": "read_bit",
        "bitmask": "0x40",
        "value_source": "major-loop EST monitor enable flag",
        "routine_label": "LA51B run path",
        "transition_context": "EST monitor gate",
        "candidate_role": "est_monitor_enable",
        "bypass_state": "not direct bypass control",
        "est_state": "monitor disabled if clear",
        "run_state": "running/run-fuel path",
        "fault_state": "monitor gated",
        "required_for_minimal_os": "yes_if_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "source comment: MAJOR LOOP EST MONITOR ENABLE",
    },
    {
        "stage": "post_la906_first_drp_gate",
        "pc": "0xABCB",
        "mnemonic": "BRCLR",
        "operands": "L0044,#$08,LAC31",
        "symbol": "L0044 bit3",
        "address": "0x0044",
        "read_or_write": "read_bit",
        "bitmask": "0x08",
        "value_source": "first DRP valid latch",
        "routine_label": "LABA2 / post-LA906 EST check",
        "transition_context": "post_la906_fault_monitor_gate",
        "candidate_role": "drp_count_gate",
        "bypass_state": "no EST check if no first DRP valid",
        "est_state": "EST check gated by first DRP valid",
        "run_state": "requires first DRP valid",
        "fault_state": "fault check skipped if clear",
        "required_for_minimal_os": "yes_if_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "gate occurs after LA906 output sequence rows; this suggests LA906 can run before monitor acceptance",
    },
    {
        "stage": "post_la906_drp_occurred_gate",
        "pc": "0xABCF",
        "mnemonic": "BRCLR",
        "operands": "L0050,#$04,LAC10",
        "symbol": "L0050 bit2",
        "address": "0x0050",
        "read_or_write": "read_bit",
        "bitmask": "0x04",
        "value_source": "DRP occurred 6.25 ms test flag",
        "routine_label": "LABA2 / post-LA906 EST check",
        "transition_context": "post_la906_fault_monitor_gate",
        "candidate_role": "drp_count_gate",
        "bypass_state": "not direct bypass control",
        "est_state": "EST check gated by recent DRP",
        "run_state": "requires recent DRP",
        "fault_state": "fault check skipped if clear",
        "required_for_minimal_os": "yes_if_fault_monitor_retained",
        "confidence": "medium_high_static",
        "notes": "source comment: DRP OCCURRED 6.25msec TEST",
    },
    {
        "stage": "est_monitor_sample_read",
        "pc": "0xABD3",
        "mnemonic": "LDD",
        "operands": "L3FCA",
        "symbol": "L3FCA",
        "address": "0x3FCA",
        "read_or_write": "read",
        "bitmask": "",
        "value_source": "ASIC/RPM/ref count source",
        "routine_label": "LABA2 / EST monitor A",
        "transition_context": "Error 42 A monitor sample",
        "candidate_role": "asic_status_read",
        "bypass_state": "not direct bypass control",
        "est_state": "monitor sample source",
        "run_state": "run/DRP-valid context",
        "fault_state": "ERR42 sample source",
        "required_for_minimal_os": "yes_if_fault_monitor_retained",
        "confidence": "medium_static",
        "notes": "sample is compared against L0205; user-watch L0204 is adjacent but static rows point to L0205 here",
    },
    {
        "stage": "est_monitor_prior_sample_compare",
        "pc": "0xABEA",
        "mnemonic": "SUBD",
        "operands": "L0205",
        "symbol": "L0205",
        "address": "0x0205",
        "read_or_write": "read",
        "bitmask": "",
        "value_source": "prior L3FCA sample",
        "routine_label": "LABA2 / EST monitor A",
        "transition_context": "Error 42 A monitor delta",
        "candidate_role": "est_fault_counter",
        "bypass_state": "not direct bypass control",
        "est_state": "monitoring",
        "run_state": "run/DRP-valid context",
        "fault_state": "compare current vs prior sample",
        "required_for_minimal_os": "yes_if_fault_monitor_retained",
        "confidence": "medium_static",
        "notes": "important correction: static evidence points to L0205/L022C, not L0204/L022B, for this EST monitor path",
    },
    {
        "stage": "est_error_counter_increment",
        "pc": "0xAC06/0xAC07",
        "mnemonic": "INCB/STAB",
        "operands": "L022C",
        "symbol": "L022C",
        "address": "0x022C",
        "read_or_write": "write",
        "bitmask": "",
        "value_source": "incremented EST error counter",
        "routine_label": "LABFE / EST monitor A",
        "transition_context": "Error 42 A counter",
        "candidate_role": "est_fault_counter",
        "bypass_state": "not direct bypass control",
        "est_state": "monitoring",
        "run_state": "run/DRP-valid context",
        "fault_state": "ERR42A counter increment",
        "required_for_minimal_os": "yes_if_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "source comments identify EST ERR CNTR and threshold L4E72=4 NUM EST ERR'S FR 42A",
    },
    {
        "stage": "est_monitor_sample_store",
        "pc": "0xAC0D",
        "mnemonic": "STX",
        "operands": "L0205",
        "symbol": "L0205",
        "address": "0x0205",
        "read_or_write": "write",
        "bitmask": "",
        "value_source": "X=current L3FCA sample",
        "routine_label": "LAC0D / EST monitor A",
        "transition_context": "Error 42 A monitor sample store",
        "candidate_role": "est_fault_counter",
        "bypass_state": "not direct bypass control",
        "est_state": "monitoring",
        "run_state": "run/DRP-valid context",
        "fault_state": "store prior sample for next compare",
        "required_for_minimal_os": "yes_if_fault_monitor_retained",
        "confidence": "medium_static",
        "notes": "stores current sample for next EST monitor comparison",
    },
    {
        "stage": "est_monitor_enable_set_good_path",
        "pc": "0xAC1C",
        "mnemonic": "BSET",
        "operands": "L004F,#$40",
        "symbol": "L004F bit6",
        "address": "0x004F",
        "read_or_write": "write_bit",
        "bitmask": "0x40",
        "value_source": "good EST monitor path",
        "routine_label": "LAC1C / EST monitor A",
        "transition_context": "EST monitor enable",
        "candidate_role": "est_monitor_enable",
        "bypass_state": "not direct bypass control",
        "est_state": "monitor enabled",
        "run_state": "run/DRP-valid context",
        "fault_state": "good path clears error counter",
        "required_for_minimal_os": "yes_if_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "source comment: SET b6, MAJOR LOOP EST MONITOR ENABLE",
    },
    {
        "stage": "est_error_counter_clear_good_path",
        "pc": "0xAC1F",
        "mnemonic": "CLR",
        "operands": "L022C",
        "symbol": "L022C",
        "address": "0x022C",
        "read_or_write": "write",
        "bitmask": "",
        "value_source": "good EST monitor path",
        "routine_label": "LAC1C / EST monitor A",
        "transition_context": "EST monitor enable",
        "candidate_role": "est_fault_counter",
        "bypass_state": "not direct bypass control",
        "est_state": "monitor enabled",
        "run_state": "run/DRP-valid context",
        "fault_state": "clear EST error counter",
        "required_for_minimal_os": "yes_if_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "clears EST ERR CNTR",
    },
    {
        "stage": "first_drp_valid_clear_after_monitor",
        "pc": "0xAC25",
        "mnemonic": "BCLR",
        "operands": "L0044,#$08",
        "symbol": "L0044 bit3",
        "address": "0x0044",
        "read_or_write": "write_bit",
        "bitmask": "0x08",
        "value_source": "post-monitor event consumed",
        "routine_label": "LAC25 / event rearm",
        "transition_context": "DRP event rearm / monitor completion",
        "candidate_role": "drp_count_gate",
        "bypass_state": "event consumed",
        "est_state": "ready for next event",
        "run_state": "run/DRP-valid context",
        "fault_state": "not_fault_path",
        "required_for_minimal_os": "yes_if_stock_event_latch_retained",
        "confidence": "high_static",
        "notes": "source comment: CLR b3, 1st DRP VALID",
    },
    {
        "stage": "asic_status_mirror_read",
        "pc": "0xAC28",
        "mnemonic": "LDX",
        "operands": "L3FEC",
        "symbol": "L3FEC",
        "address": "0x3FEC",
        "read_or_write": "read",
        "bitmask": "",
        "value_source": "ASIC source/status/capture",
        "routine_label": "LAC25 / status mirror",
        "transition_context": "ASIC status/mirror after EST monitor",
        "candidate_role": "asic_status_read",
        "bypass_state": "not direct bypass control",
        "est_state": "handoff/ack context",
        "run_state": "run/DRP-valid context",
        "fault_state": "status sync",
        "required_for_minimal_os": "likely_yes_until_bench_disproves",
        "confidence": "medium_static",
        "notes": "read side of $3FEC->$3FE4 mirror",
    },
    {
        "stage": "asic_status_mirror_write",
        "pc": "0xAC2E",
        "mnemonic": "STX",
        "operands": "L3FE4",
        "symbol": "L3FE4",
        "address": "0x3FE4",
        "read_or_write": "write",
        "bitmask": "",
        "value_source": "X=$3FEC",
        "routine_label": "LAC25 / status mirror",
        "transition_context": "ASIC status/mirror after EST monitor",
        "candidate_role": "asic_mirror_ack",
        "bypass_state": "not direct bypass control",
        "est_state": "handoff/ack context",
        "run_state": "run/DRP-valid context",
        "fault_state": "status sync",
        "required_for_minimal_os": "likely_yes_until_bench_disproves",
        "confidence": "medium_static",
        "notes": "write side of $3FEC->$3FE4 mirror; may be ack/status sync rather than bypass authority itself",
    },
    {
        "stage": "major_loop_est_monitor_gate",
        "pc": "0xE019",
        "mnemonic": "BRCLR",
        "operands": "L004F,#$40,LE041",
        "symbol": "L004F bit6",
        "address": "0x004F",
        "read_or_write": "read_bit",
        "bitmask": "0x40",
        "value_source": "major-loop EST monitor enable flag",
        "routine_label": "LE011 / EST monitor B",
        "transition_context": "major_loop_Error_42_monitor",
        "candidate_role": "est_monitor_enable",
        "bypass_state": "not direct bypass control",
        "est_state": "major monitor gated by bit6",
        "run_state": "run/fault monitor context",
        "fault_state": "skip ERR42B if clear",
        "required_for_minimal_os": "yes_if_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "second EST monitor path confirms L004F bit6 as monitor enable, not necessarily EST authority output bit",
    },
    {
        "stage": "major_loop_err42_rpm_gate",
        "pc": "0xE023",
        "mnemonic": "CMPA",
        "operands": "L4E70",
        "symbol": "L4E70",
        "address": "0x4E70",
        "read_or_write": "read_cal_compare",
        "bitmask": "",
        "value_source": "A=RPM/25",
        "routine_label": "LE011 / EST monitor B",
        "transition_context": "major_loop_Error_42_monitor",
        "candidate_role": "rpm_threshold_gate",
        "bypass_state": "not direct bypass control",
        "est_state": "major monitor active above threshold",
        "run_state": "RPM gate",
        "fault_state": "ERR42B RPM gate",
        "required_for_minimal_os": "yes_if_fault_monitor_retained",
        "confidence": "high_static",
        "notes": "source comment: RPM LIMIT, 450 RPM, ERR 42",
    },
]

FIELDS = [
    "stage", "pc", "mnemonic", "operands", "symbol", "address",
    "read_or_write", "bitmask", "value_source", "routine_label",
    "transition_context", "candidate_role", "bypass_state", "est_state",
    "run_state", "fault_state", "required_for_minimal_os", "confidence", "notes",
]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def resolve(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else repo_root() / p


def require(path: str | Path) -> None:
    p = resolve(path)
    if not p.exists():
        raise FileNotFoundError(p)


def write_csv(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(ROWS)


def write_md(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Spark BYPASS / EST Transition",
        "",
        "## Purpose",
        "",
        "Document the crank-to-run and bypass-to-EST authority transition required before the minimal OS may command spark through the ASIC/EST handoff path.",
        "",
        "This is an authority-transfer contract, not spark math and not a spark writer.",
        "",
        "## Problem",
        "",
        "`LA906` depends on rolling spark state. If `$3FF6/$3FDC` are only globally cleared at key-on, the first run-mode spark handoff may be unsafe unless stock code delays EST authority until valid period/rolling state exists.",
        "",
        "## Scope",
        "",
        "- crank/bypass state",
        "- run qualification",
        "- DRP/ref event qualification",
        "- EST enable/monitor behavior",
        "- Error 42 counter behavior",
        "- ASIC status/mirror behavior related to spark authority",
        "",
        "## Baseline Map",
        "",
        "This pass uses the committed static baseline:",
        "",
        "```text",
        "maps/full/hardware_access_map_v0.2.csv",
        "```",
        "",
        "Do not reference `hardware_access_map_v0.3.csv` until it is generated and committed.",
        "",
        "## Candidate State",
        "",
        "| Symbol | Candidate role | Evidence | Confidence |",
        "|---|---|---|---|",
        "| `L004F bit7` | engine_running | clear at `0x7D78`, tested at `0xA510`, set at `0xA56E` | high_static |",
        "| `L004F bit6` | EST monitor enable | tested at `0xA51B` and `0xE019`, set at `0xAC1C` | high_static |",
        "| `L004F bit4` | run fuel / run-state gate | clear at `0x7D7B`, tested at `0xA514` | medium_high_static |",
        "| `L0044 bit3` | first DRP valid latch | set at `0xA544`, tested at `0xA540/0xABCB`, cleared at `0xAC25` | high_static |",
        "| `L0210` | run qualification event counter | incremented at `0xA560`, compared at `0xA566` | medium_high_static |",
        "| `L4133` | 450 RPM bypass-to-run threshold candidate | compared at `0xA554` | high_static |",
        "| `L3FCA` | ASIC/ref count sample source | sampled at `0xABD3` | medium_static |",
        "| `L0205` | prior `L3FCA` sample | compared at `0xABEA`, stored at `0xAC0D` | medium_static |",
        "| `L022C` | EST Error 42 counter candidate | incremented at `0xAC06/0xAC07`, cleared at `0xAC1F` | high_static |",
        "| `L3FEC` | ASIC status/source | read at `0xAC28` | medium_static |",
        "| `L3FE4` | ASIC mirror/ack target | written from `$3FEC` at `0xAC2E` | medium_static |",
        "| `L022B` | watched legacy Error 42 candidate | not primary in captured EST monitor rows; primary rows point to `L022C` | low_for_this_path |",
        "| `L0204` | watched prior sample candidate | adjacent to `L0205`; captured EST monitor rows use `L0205` | low_for_this_path |",
        "",
        "## Transition Rows",
        "",
        "| Stage | PC | Instruction | Symbol | Role | Required? | Confidence |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in ROWS:
        inst = f"{row['mnemonic']} {row['operands']}".strip()
        lines.append(f"| {row['stage']} | `{row['pc']}` | `{inst}` | `{row['symbol']}` | {row['candidate_role']} | {row['required_for_minimal_os']} | {row['confidence']} |")
    lines += [
        "",
        "## Static Transition Model",
        "",
        "```text",
        "key-on/stall/reset:",
        "  L004F bit7 ENGINE RUNNING cleared",
        "  L004F bit4 RUN FUEL cleared",
        "  L0044 bit3 FIRST DRP VALID cleared/rearmed",
        "",
        "crank / first-ref acceptance:",
        "  first DRP/ref event sets L0044 bit3",
        "  L3FC0 provides period/counter basis upstream of run qualification",
        "",
        "run qualification:",
        "  compare period/ref value against L4133 450 RPM bypass-to-run threshold",
        "  increment L0210 qualifying event counter",
        "  compare L0210 against L4142 count threshold",
        "  set L004F bit7 ENGINE RUNNING when threshold + count gates pass",
        "  clear startup spark override L01F2",
        "",
        "post-LA906 EST monitor / status path:",
        "  require first DRP valid and recent DRP occurrence before EST monitor checks",
        "  sample L3FCA and compare against stored L0205",
        "  increment/clear L022C EST error counter depending on result",
        "  set L004F bit6 major-loop EST monitor enable on good path",
        "  clear first DRP valid after event is consumed",
        "  mirror L3FEC to L3FE4",
        "```",
        "",
        "## Required Questions",
        "",
        "- What exact condition declares engine running?",
        "- How many DRP/ref events are required before run?",
        "- What RPM threshold enables EST handoff?",
        "- Does `LA906` execute before or after EST authority transfer?",
        "- Is bypass physically controlled by a CPU/ASIC write or by ASIC state?",
        "- What increments Error 42 counter?",
        "- What clears Error 42 counter?",
        "- Does `$3FEC->$3FE4` participate in EST authority transfer?",
        "",
        "## Current Static Answers",
        "",
        "```text",
        "engine running:",
        "  L004F bit7 is the strongest static engine-running flag.",
        "",
        "run qualification:",
        "  static evidence supports RPM threshold plus DRP/ref event-count gating.",
        "",
        "450 RPM threshold:",
        "  L4133 is explicitly commented as 450 RPM BYPASS TO RUN ENABLE IN REF PERIOD.",
        "",
        "EST monitor enable:",
        "  L004F bit6 is major-loop EST monitor enable, not yet proven to be the physical EST/bypass output control.",
        "",
        "Error 42 path:",
        "  captured EST monitor rows point to L3FCA -> L0205 comparison and L022C counter, not L0204/L022B as the primary path.",
        "",
        "LA906 before authority:",
        "  post-LA906 gates at 0xABCB/0xABCF suggest LA906 may prepare timing state before monitor acceptance. Bench must determine whether coil authority is still physically bypassed/ignored.",
        "",
        "ASIC mirror:",
        "  $3FEC->$3FE4 appears after EST monitor/event consumption; treat as required sync/ack until bench disproves it.",
        "```",
        "",
        "## Minimal-OS Requirement",
        "",
        "The minimal OS must not command EST spark until:",
        "",
        "1. REF/DRP period is valid.",
        "2. rolling spark state is seeded or known safe.",
        "3. bypass/EST authority transition is safe.",
        "4. missing-ref/dropout behavior is defined.",
        "5. EST fault monitoring cannot falsely trip from missing factory state.",
        "",
        "## Static Classification",
        "",
        "```text",
        "BYP-A:",
        "  not sufficient alone. Static evidence shows more than RPM threshold.",
        "",
        "BYP-B:",
        "  strongest static fit. Transfer/run qualification requires RPM threshold plus DRP/ref event count.",
        "",
        "BYP-C:",
        "  possible. $3FEC->$3FE4 mirror may participate in status/ack but is not yet proven as authority gate.",
        "",
        "BYP-D:",
        "  plausible. LA906 appears able to prepare timing commands before EST monitor acceptance; coil effect must be bench-proven.",
        "",
        "BYP-E:",
        "  supported with corrected variables: Error 42 monitor depends on $3FCA/L0205/L022C in captured rows.",
        "",
        "BYP-F:",
        "  still possible until bypass wire and EST output are scoped through crank-to-run.",
        "```",
        "",
        "## Future Module Boundary",
        "",
        "If bench confirms this model, spark should split into:",
        "",
        "```text",
        "SPARK_BYPASS_INIT",
        "SPARK_RUN_QUALIFY",
        "SPARK_ENABLE_EST_AUTHORITY",
        "SPARK_FAULT_MONITOR",
        "```",
        "",
        "separate from:",
        "",
        "```text",
        "SPARK_CONVERT",
        "SPARK_ROLLING_UPDATE",
        "SPARK_ASIC_HANDOFF",
        "```",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--source", default="source/31/BMHM_HAC_ORG_7100_to_end.asm")
    p.add_argument("--map", default="maps/full/hardware_access_map_v0.2.csv")
    p.add_argument("--name", default="SPARK_BYPASS_EST_TRANSITION")
    p.add_argument("--watch", action="append", default=[])
    p.add_argument("--out-md", required=True)
    p.add_argument("--out-csv", required=True)
    args = p.parse_args()

    require(args.source)
    require(args.map)
    write_csv(resolve(args.out_csv))
    write_md(resolve(args.out_md))
    print(f"{args.name}: wrote {len(ROWS)} transition rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
