#!/usr/bin/env python3
"""Build the minimal OS module boundary contract.

This combines the currently mapped fuel and spark output contracts with the next
unmapped hardware subsystem boundary. It does not generate runtime ASM.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

ROWS = [
    {
        "module": "RESET_INIT",
        "status": "partial_static",
        "source_contract": "EFI_OUTPUT_INIT_ROUTINE; SPARK_INIT_STATE; ASIC_HARDWARE_REGISTER_CONTRACT",
        "runtime_inputs": "reset vector; power-on state; hardware register relocation needs; ASIC window state",
        "runtime_outputs": "HC11 register relocation; stack; ASIC clear/default state; output-safe defaults; SCI/ALDL base state; watchdog base state",
        "state_owned": "init phase state; output safe defaults; boot sequencing flags",
        "hardware_registers": "$3FC0-$3FF8 clear window candidate; HC11 INIT/register block; watchdog/SPI/SCI registers pending full contract",
        "required_static": "HC11 relocation; stack; safe defaults; ASIC/window clear candidate",
        "bench_gated": "ASIC init side effects; required $3FCC/$3FEA EFI output state; spark $3FF6/$3FDC first seed; exact watchdog service needs",
        "not_yet_mapped": "complete watchdog/reset service; SCI/ALDL init contract; all global ASIC mode bits",
        "forbidden_until_proven": "do not add random GM mode-word baggage; do not assume $3FCC/$3FEA mandatory runtime fuel companions",
        "risk_if_wrong": "wrong init can leave outputs enabled, disable ASIC handoff, corrupt spark first event, or trip watchdog/reset",
        "next_contract": "WATCHDOG_SAFE_STATE_CONTRACT or ALDL_DEBUG_CONTRACT after IAC",
        "notes": "reset/init is the owner of one-time hardware state, not per-event fuel/spark math",
    },
    {
        "module": "SENSOR_ACQUIRE",
        "status": "planned_not_fully_contracted",
        "source_contract": "STATIC_ANALYSIS_SUMMARY; VARIABLE_DEPENDENCY_GRAPH; CALIBRATION_LAYOUT",
        "runtime_inputs": "MAP; TPS; CTS; O2; battery voltage; REF/DRP period; optional MAT if retained",
        "runtime_outputs": "filtered sensor values; plausibility/default flags; battery correction inputs; RPM/load basis",
        "state_owned": "raw ADC values; filtered values; default/fault flags; sensor update cadence",
        "hardware_registers": "ADC/input ASIC registers pending focused contract",
        "required_static": "sensor values needed by fuel, spark, idle, and correction logic",
        "bench_gated": "ADC register addresses; scaling; update cadence; default behavior",
        "not_yet_mapped": "focused ADC/sensor hardware contract",
        "forbidden_until_proven": "do not copy full GM diagnostic strategy unless hardware-required",
        "risk_if_wrong": "bad sensor acquisition corrupts fuel/spark/idle decisions and safe-state behavior",
        "next_contract": "SENSOR_ADC_INPUT_CONTRACT",
        "notes": "sensor acquisition should be separated from output control modules",
    },
    {
        "module": "REF_RPM_PERIOD",
        "status": "partial_static",
        "source_contract": "SPARK_TIMEBASE_PERIOD_CONTRACT; SPARK_BYPASS_EST_TRANSITION; SPARK_INIT_STATE",
        "runtime_inputs": "REF/DRP input; ASIC period/capture values; first/recent DRP latches",
        "runtime_outputs": "RPM; period basis L005F/L0060; first DRP valid; recent DRP valid; run qualification inputs",
        "state_owned": "L3FC0 source interpretation; L005F/L0060 period basis; first/recent DRP state; qualifying event count L0210",
        "hardware_registers": "$3FC0; $3FCA; related ASIC capture/status registers pending bench",
        "required_static": "valid period basis before fuel/spark runtime decisions; run qualification inputs",
        "bench_gated": "physical period unit; L3FC0 anchor meaning; missing-ref/dropout behavior; exact event latches",
        "not_yet_mapped": "complete REF ISR/capture contract",
        "forbidden_until_proven": "do not allow spark EST authority without valid REF/DRP period",
        "risk_if_wrong": "wild spark timing, bad RPM/load state, false run qualification, unsafe dropout behavior",
        "next_contract": "REF_RPM_PERIOD_CONTRACT",
        "notes": "this module feeds both spark conversion and run/bypass authority",
    },
    {
        "module": "FUEL_OUTPUT",
        "status": "static_ready_bench_pending",
        "source_contract": "EFI_PW_3FCE_CONTRACT; EFI_PW_UNITS; EFI_OUTPUT_COMPANION_REGISTERS; EFI_OUTPUT_INIT_STATE; MINIMAL_EFI_PW_WRITER; EFI_OUTPUT_INIT_ROUTINE",
        "runtime_inputs": "final EFI pulsewidth command in 1/65536-second units; fuel enable/no-fuel state; EFI output init state",
        "runtime_outputs": "STD $3FCE runtime EFI pulsewidth handoff; zero/off command candidate",
        "state_owned": "EFI_OUTPUT_INIT state; runtime pulsewidth command boundary only",
        "hardware_registers": "$3FCE/$3FCF; possible init-only $3FCC/$3FEA; ASIC clear window",
        "required_static": "EFI_PW_WRITE: D -> STD $3FCE; counts = seconds * 65536",
        "bench_gated": "$3FCE controls injector PW; zero command behavior; whether companion init is required; Path A vs Path A-with-init",
        "not_yet_mapped": "full fuel math, injector correction, AE/PE/DFCO strategy inputs",
        "forbidden_until_proven": "do not add per-pulse $3FCC/$3FEA companions unless bench proves runtime need",
        "risk_if_wrong": "wrong fuel pulsewidth, injectors stuck on/off, no fuel during crank/run, unsafe rich/lean output",
        "next_contract": "FUEL_MATH_MODULE_BOUNDARY after hardware outputs are bench-proven",
        "notes": "fuel output has the cleanest runtime writer candidate in the project so far",
    },
    {
        "module": "SPARK_OUTPUT",
        "status": "boundary_only_no_asm",
        "source_contract": "SPARK_MINIMAL_MODULE_BOUNDARY; SPARK_CONVERSION_EQUATION; SPARK_LA906_OUTPUT_SEQUENCE; SPARK_ROLLING_STATE_MODEL; SPARK_INIT_STATE; SPARK_BYPASS_EST_TRANSITION; SPARK_EST_FAULT_MONITOR_CONTRACT; source/minimal_os/spark/README.md",
        "runtime_inputs": "desired spark degrees; REF/DRP period; run qualification; bypass/EST state; L0201 latency; L3FC0 anchor; rolling state $3FF6/$3FDC/L01EC",
        "runtime_outputs": "$3FE8/$3FE6 paired timing writes; $3FF6/$3FDC rolling updates; possible $3FEC->$3FE4 mirror; EST authority permission",
        "state_owned": "run qualify; bypass/EST authority; degree-to-time conversion; rolling state; ASIC handoff; optional EST monitor",
        "hardware_registers": "$3FE8; $3FE6; $3FF6; $3FDC; $3FEC; $3FE4; $3FC0; $3FCA",
        "required_static": "run qualification; bypass/EST authority; conversion equation; rolling state; paired $3FE8/$3FE6 handoff likely required",
        "bench_gated": "$3FE8/$3FE6 paired role; $3FEC->$3FE4 mirror; physical bypass authority; first-event seed; L0201/L3FC0 packing; Error 42 side effects",
        "not_yet_mapped": "physical bypass/EST output control register/line; full dropout behavior; final spark writer sequence",
        "forbidden_until_proven": "no SPARK_WRITE; no direct $3FE8/$3FE6 writer; no LA906 replacement ASM; no physical EST authority code",
        "risk_if_wrong": "wild spark timing, loss of bypass safety, false EST fault, coil misfire, engine damage",
        "next_contract": "bench classification before any spark ASM; then source/minimal_os/spark static stubs only if explicitly marked",
        "notes": "spark is structurally mapped but still blocked from code by bench gates",
    },
    {
        "module": "IDLE_AIR_OUTPUT",
        "status": "next_unmapped_subsystem",
        "source_contract": "none_focused_yet",
        "runtime_inputs": "desired IAC position; present IAC position; idle/crank/run state; step rate; park/crank target; battery/CTS if retained",
        "runtime_outputs": "IAC step direction; coil phase/latch sequence; present-count update; park/default position commands",
        "state_owned": "IAC desired counts; present counts; stepper phase; direction; step cadence; park/crank/run behavior",
        "hardware_registers": "IAC stepper ASIC/output registers pending; possible $3FFC/output latch; direct-page IAC RAM state pending",
        "required_static": "not yet mapped",
        "bench_gated": "coil phase sequence; output latch addresses; step timing; reset/park behavior; lost-step assumptions",
        "not_yet_mapped": "full IAC/idle-air output hardware contract",
        "forbidden_until_proven": "no IAC writer until output registers and phase sequence are extracted",
        "risk_if_wrong": "stuck IAC, runaway idle, no start airflow, lost step position, driver overheating",
        "next_contract": "IAC_IDLE_AIR_OUTPUT_CONTRACT",
        "notes": "next technical pass should target hardware output sequence, not idle strategy tables",
    },
    {
        "module": "ALDL_DEBUG",
        "status": "planned",
        "source_contract": "DYNAMIC_TRACE_PLAN; ALDL_DEBUG future contract",
        "runtime_inputs": "module state; hardware write trace candidates; safe debug cadence; ALDL request/response state",
        "runtime_outputs": "debug frames; trace visibility; module-state exports; bench instrumentation frames",
        "state_owned": "debug page/frame selection; ALDL transmit state; trace counters",
        "hardware_registers": "SCI/ALDL hardware registers pending focused contract",
        "required_static": "debug visibility needed for bench proof but not core engine output",
        "bench_gated": "serial timing; request/response side effects; bandwidth limits; live trace safety",
        "not_yet_mapped": "minimal ALDL frame contract and optional debug registers",
        "forbidden_until_proven": "do not let debug writes perturb timing-critical outputs",
        "risk_if_wrong": "bad bench evidence, serial lockups, timing jitter, hidden output side effects",
        "next_contract": "ALDL_DEBUG_CONTRACT",
        "notes": "debug must help prove hardware contracts without becoming required engine strategy",
    },
    {
        "module": "WATCHDOG_SAFE_STATE",
        "status": "required_not_fully_contracted",
        "source_contract": "MINIMAL_OS_SKELETON; STATIC_ANALYSIS_SUMMARY; future watchdog/safe-state contract",
        "runtime_inputs": "run state; REF present/missing; fuel enable; spark authority; IAC state; watchdog timer state",
        "runtime_outputs": "watchdog service; no-ref fuel-off; spark/bypass safe state; IAC default/safe state; reset/fault response",
        "state_owned": "safe-state flags; dropout handling; watchdog service cadence; output disable/hold policy",
        "hardware_registers": "watchdog register(s) pending; fuel/spark/IAC output registers as safe-state targets",
        "required_static": "no-ref safe state; fuel-off safe state; spark/bypass safe state; watchdog service required",
        "bench_gated": "watchdog service exact sequence; dropout behavior; output disable vs hold decisions; IAC safe state",
        "not_yet_mapped": "watchdog hardware contract; complete safe-state transition table",
        "forbidden_until_proven": "do not disable watchdog or leave outputs live during missing REF unless explicitly proven safe",
        "risk_if_wrong": "watchdog reset loop, stuck injector, unsafe spark, runaway idle, bench damage",
        "next_contract": "WATCHDOG_SAFE_STATE_CONTRACT",
        "notes": "safe-state behavior cuts across every output module",
    },
    {
        "module": "TRANSMISSION_EMISSIONS_EXCLUDED",
        "status": "excluded_unless_hardware_required",
        "source_contract": "README; WORKING_STATE",
        "runtime_inputs": "none for minimal OS unless hardware-required",
        "runtime_outputs": "none planned",
        "state_owned": "none planned",
        "hardware_registers": "TCC/shift/EGR/EVAP outputs excluded unless proven required for shared hardware init",
        "required_static": "none",
        "bench_gated": "only if a supposedly excluded output shares required ASIC mode/init behavior",
        "not_yet_mapped": "not targeted",
        "forbidden_until_proven": "no TCC; no shift logic; no EGR; no EVAP; no inherited GM mode-word baggage",
        "risk_if_wrong": "scope creep and strategy swamp; accidental hardware side effects if shared mode bits ignored",
        "next_contract": "none unless hardware-required evidence appears",
        "notes": "keeps project focused on required hardware contracts",
    },
]

FIELDS = [
    "module", "status", "source_contract", "runtime_inputs", "runtime_outputs",
    "state_owned", "hardware_registers", "required_static", "bench_gated",
    "not_yet_mapped", "forbidden_until_proven", "risk_if_wrong", "next_contract", "notes",
]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def resolve(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else repo_root() / p


def require(path: str | Path) -> None:
    p = resolve(path)
    if not p.exists():
        raise FileNotFoundError(p)


def write_csv(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(ROWS)


def write_md(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Minimal OS Module Boundary",
        "",
        "## Purpose",
        "",
        "Define the OS-level module boundary for the clean 7427 hardware-contract minimal OS.",
        "",
        "This contract combines the mapped fuel and spark output contracts with the next unmapped hardware subsystem. It does not create new ASM runtime code.",
        "",
        "## Module Classes",
        "",
        "```text",
        "static-ready:",
        "  statically mapped enough to define a provisional module/API, but still bench-pending.",
        "",
        "bench-gated:",
        "  likely required but must be scoped/bench-proven before implementation.",
        "",
        "not yet mapped:",
        "  do not implement. Create a focused hardware-output/input contract first.",
        "",
        "forbidden until proven:",
        "  do not add strategy baggage or direct hardware writes without contract evidence.",
        "```",
        "",
        "## Top-Level Module Map",
        "",
        "| Module | Status | Runtime outputs | Next contract |",
        "|---|---|---|---|",
    ]
    for r in ROWS:
        lines.append(f"| `{r['module']}` | {r['status']} | {r['runtime_outputs']} | {r['next_contract']} |")

    lines += [
        "",
        "## RESET_INIT",
        "",
        "Owns:",
        "",
        "```text",
        "HC11 register relocation",
        "stack",
        "ASIC window clear",
        "output safe defaults",
        "watchdog setup",
        "SCI/ALDL setup",
        "```",
        "",
        "Status: `partial`.",
        "",
        "Bench gates:",
        "",
        "```text",
        "ASIC init side effects",
        "required $3FCC/$3FEA EFI output state",
        "spark rolling-state first seed",
        "watchdog service sequence",
        "```",
        "",
        "## SENSOR_ACQUIRE",
        "",
        "Owns ADC/raw-input acquisition, filtering/defaulting, and sensor-state exports to fuel, spark, idle, and safe-state modules.",
        "",
        "Status: `planned_not_fully_contracted`.",
        "",
        "Next focused contract:",
        "",
        "```text",
        "SENSOR_ADC_INPUT_CONTRACT",
        "```",
        "",
        "## REF_RPM_PERIOD",
        "",
        "Owns REF/DRP period/capture state and the period basis used by spark and run qualification.",
        "",
        "Current known state:",
        "",
        "```text",
        "$3FC0 = period/capture source candidate",
        "L005F/L0060 = spark period basis",
        "L0044 bit3 = first DRP valid latch",
        "L0050 bit2 = recent DRP occurred gate",
        "L0210 = qualifying DRP/ref event counter",
        "```",
        "",
        "Status: `partial_static`.",
        "",
        "## FUEL_OUTPUT",
        "",
        "Status: `static-ready / bench-pending`.",
        "",
        "Owns:",
        "",
        "```text",
        "EFI_OUTPUT_INIT",
        "EFI_PW_WRITE",
        "```",
        "",
        "Required runtime output:",
        "",
        "```asm",
        "; D = EFI pulsewidth in 1/65536 second units",
        "STD $3FCE",
        "```",
        "",
        "Hard boundary:",
        "",
        "```text",
        "Fuel may have a provisional runtime writer.",
        "Do not add per-pulse companion writes unless bench proves they are required.",
        "```",
        "",
        "Bench gates:",
        "",
        "```text",
        "$3FCE controls injector PW",
        "zero command behavior",
        "whether companion init is required",
        "```",
        "",
        "## SPARK_OUTPUT",
        "",
        "Status: `boundary-only / no ASM`.",
        "",
        "Owns:",
        "",
        "```text",
        "run qualification",
        "bypass/EST authority",
        "degree-to-time conversion",
        "rolling state",
        "ASIC handoff",
        "optional EST monitor",
        "dropout-safe behavior",
        "```",
        "",
        "Likely required outputs:",
        "",
        "```text",
        "$3FE8",
        "$3FE6",
        "$3FF6",
        "$3FDC",
        "```",
        "",
        "Bench gates:",
        "",
        "```text",
        "$3FE8/$3FE6 paired role",
        "$3FEC->$3FE4 mirror",
        "physical bypass authority",
        "first-event seed",
        "L0201/L3FC0 packing",
        "Error 42 side effects",
        "dropout/missing-REF safe behavior",
        "```",
        "",
        "Hard boundary:",
        "",
        "```text",
        "No SPARK_WRITE.",
        "No direct $3FE8/$3FE6 writer.",
        "No LA906 replacement ASM.",
        "No physical EST authority code.",
        "```",
        "",
        "## IDLE_AIR_OUTPUT",
        "",
        "Status: `next unmapped subsystem`.",
        "",
        "Owns:",
        "",
        "```text",
        "IAC present position",
        "desired position",
        "step direction",
        "phase/latch output",
        "park/crank/run behavior",
        "```",
        "",
        "Likely targets:",
        "",
        "```text",
        "IAC stepper ASIC/output registers",
        "IAC RAM state",
        "idle state flags",
        "$3Fxx ASIC/output registers",
        "$3FFC output latch candidate",
        "```",
        "",
        "Next contract:",
        "",
        "```text",
        "IAC_IDLE_AIR_OUTPUT_CONTRACT",
        "```",
        "",
        "Hard boundary:",
        "",
        "```text",
        "No IAC writer until output registers and phase sequence are extracted.",
        "```",
        "",
        "## ALDL_DEBUG",
        "",
        "Status: `planned`.",
        "",
        "Owns debug frames, hardware trace visibility, and module-state exports for bench validation. It must not perturb timing-critical output behavior.",
        "",
        "## WATCHDOG_SAFE_STATE",
        "",
        "Status: `required but not fully contracted`.",
        "",
        "Owns:",
        "",
        "```text",
        "watchdog service",
        "no-ref safe state",
        "fuel-off safe state",
        "spark/bypass safe state",
        "IAC safe/default state",
        "```",
        "",
        "Hard boundary:",
        "",
        "```text",
        "Do not disable watchdog or leave outputs live during missing REF unless explicitly proven safe.",
        "```",
        "",
        "## Excluded Unless Hardware-Required",
        "",
        "```text",
        "no TCC",
        "no shift logic",
        "no EGR",
        "no EVAP",
        "no inherited mode-word baggage unless proven hardware-required",
        "```",
        "",
        "## Next Technical Target",
        "",
        "Start the next focused hardware-output subsystem:",
        "",
        "```text",
        "docs/contracts/IAC_IDLE_AIR_OUTPUT_CONTRACT.md",
        "maps/contracts/iac_idle_air_output_contract.csv",
        "docs/tests/IAC_IDLE_AIR_OUTPUT_TEST.md",
        "tools/build_iac_output_contract.py",
        "```",
        "",
        "The IAC pass should trace:",
        "",
        "```text",
        "IAC desired counts",
        "IAC present counts",
        "step direction",
        "step rate",
        "coil phase sequence",
        "ASIC/output latch writes",
        "park position",
        "crank position",
        "reset behavior",
        "```",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-md", required=True)
    parser.add_argument("--out-csv", required=True)
    parser.add_argument("--name", default="MINIMAL_OS_MODULE_BOUNDARY")
    args = parser.parse_args()

    write_csv(resolve(args.out_csv))
    write_md(resolve(args.out_md))
    print(f"{args.name}: wrote {len(ROWS)} module rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
