#!/usr/bin/env python3
"""Build the IAC Init/Park contract.

This isolates how stock code seeds IAC actual/present position, desired/target
position, reset-in-work state, bad-shutdown handling, and park-down request.

It does not define A/B phase order, Enable voltage gating, idle strategy, or
create an IAC writer.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

FIELDS = [
    "stage", "pc", "mnemonic", "operands", "symbol", "address", "read_or_write",
    "value_source", "routine_label", "init_context", "park_context", "candidate_role",
    "actual_position_effect", "desired_position_effect", "enable_dependency",
    "bad_shutdown_dependency", "reset_in_work_dependency", "required_for_minimal_os",
    "confidence", "notes",
]

ROWS = [
    {
        "stage": "startup_iac_setup_entry",
        "pc": "0x73DB;0x925E-0x9263",
        "mnemonic": "JSR/LDAA/ASLA/ASLA/STAA",
        "operands": "L925E / L4EF2 / L0885",
        "symbol": "L0885",
        "address": "0x0885",
        "read_or_write": "write",
        "value_source": "L4EF2 16% TPS upper limit for closed-loop IAC, scaled left two",
        "routine_label": "L925E",
        "init_context": "startup setup after hot-restart/coolant/O2 init",
        "park_context": "not park motion",
        "candidate_role": "iac_startup_setup_threshold",
        "actual_position_effect": "none",
        "desired_position_effect": "none",
        "enable_dependency": "none direct",
        "bad_shutdown_dependency": "none direct",
        "reset_in_work_dependency": "none direct",
        "required_for_minimal_os": "maybe_for_idle_strategy_not_position_seed",
        "confidence": "high_static",
        "notes": "L925E is called from startup setup at 0x73DB; this row initializes an IAC/TPS threshold, not position",
    },
    {
        "stage": "nonvolatile_memory_bombed_actual_seed",
        "pc": "0x9266-0x926F",
        "mnemonic": "BRCLR/LDAA/STAA/JSR",
        "operands": "L0046,#$40,L9272 / L4EB0 / L0007 / L92A4",
        "symbol": "L0007",
        "address": "0x0007",
        "read_or_write": "write",
        "value_source": "L4EB0 = 145 steps IAC park down",
        "routine_label": "L925E",
        "init_context": "nonvolatile memory bombed recovery",
        "park_context": "actual position seeded to park-down count",
        "candidate_role": "iac_actual_seed_after_nvm_fail",
        "actual_position_effect": "L0007 := L4EB0 (145)",
        "desired_position_effect": "none in this row",
        "enable_dependency": "not checked here; motion not directly commanded here",
        "bad_shutdown_dependency": "independent of bad shutdown branch",
        "reset_in_work_dependency": "none direct",
        "required_for_minimal_os": "yes_as_safe_unknown_position_seed_policy",
        "confidence": "high_static",
        "notes": "If nonvolatile memory is invalid, stock code does not trust retained IAC motor position; it seeds actual to the park-down maximum value",
    },
    {
        "stage": "nonvolatile_memory_bombed_idle_cell_seed",
        "pc": "0x926F;0x92A4-0x92F0",
        "mnemonic": "JSR/LDAA/CMPA/LDAB/STAB/...",
        "operands": "L92A4; L4EB1/L4EB2/L4EB3/L4EB4/L4EB5 -> L029D/L029F/L02A0/L02A2/L02A7/L02A9/L02AA/L02AC/L02B1",
        "symbol": "IAC learned/integral cells",
        "address": "0x029D..0x02B1",
        "read_or_write": "write_multiple",
        "value_source": "IAC fail/default constants and coolant threshold",
        "routine_label": "L92A4",
        "init_context": "default IAC learned cell seeding",
        "park_context": "supports post-reset/default desired airflow state, not motor homing",
        "candidate_role": "iac_default_idle_cell_seed",
        "actual_position_effect": "none direct",
        "desired_position_effect": "none direct to L0008 in this row",
        "enable_dependency": "none direct",
        "bad_shutdown_dependency": "called after NVM fail or reset-complete path",
        "reset_in_work_dependency": "called when reset-in-work completes with L0007 at zero",
        "required_for_minimal_os": "maybe_for_initial_idle_air_model_not_output_contract",
        "confidence": "high_static",
        "notes": "Seeds park/drive/A-C default flow/integral cells using L4EB1-L4EB5; keep separate from hardware position seed",
    },
    {
        "stage": "bad_shutdown_branch_select",
        "pc": "0x9272-0x927B",
        "mnemonic": "BRSET/JSR/BRA/JSR",
        "operands": "L0004,#$08,L927B / L92F1 / L927E / L93C5",
        "symbol": "L0004 bit3",
        "address": "0x0004",
        "read_or_write": "read_bit",
        "value_source": "bad shutdown flag candidate",
        "routine_label": "L925E",
        "init_context": "startup IAC setup branch",
        "park_context": "bad-shutdown path avoids normal L92F1 adjustment and calls L93C5 setup clear",
        "candidate_role": "iac_bad_shutdown_recovery_branch",
        "actual_position_effect": "none direct",
        "desired_position_effect": "none direct",
        "enable_dependency": "bad shutdown path can clear Enable through L93C5 if reset not in work",
        "bad_shutdown_dependency": "yes",
        "reset_in_work_dependency": "L93C5 skips clear if reset-in-work bit is set",
        "required_for_minimal_os": "yes_as_recovery_policy",
        "confidence": "high_static",
        "notes": "Normal shutdown path calls L92F1; bad-shutdown path calls L93C5 which preserves phase bits and clears direction/Enable unless reset is in work",
    },
    {
        "stage": "bad_shutdown_setup_clear",
        "pc": "0x93C5-0x93CD",
        "mnemonic": "BRSET/LDAA/ANDA/STAA",
        "operands": "L0009,#$01,L93CF / L000A / #$0C / L000A",
        "symbol": "L000A",
        "address": "0x000A",
        "read_or_write": "write_masked",
        "value_source": "existing L000A masked with #$0C",
        "routine_label": "L93C5",
        "init_context": "bad shutdown / setup clear",
        "park_context": "does not move motor; preserves A/B phase only",
        "candidate_role": "iac_setup_clear_preserve_phase",
        "actual_position_effect": "none",
        "desired_position_effect": "none",
        "enable_dependency": "clears L000A bit4 unless reset-in-work is set",
        "bad_shutdown_dependency": "called from bad shutdown branch",
        "reset_in_work_dependency": "skip clear when L0009 bit0 is set",
        "required_for_minimal_os": "yes_as_safe_output_state_policy",
        "confidence": "high_static",
        "notes": "Preserves A/B phase bits2/3 and clears direction/Enable; this is setup state clearing, not park motion",
    },
    {
        "stage": "reset_in_work_service_entry",
        "pc": "0x93E1-0x93ED",
        "mnemonic": "BRCLR/CLR/TST/BEQ/JMP",
        "operands": "L0009,#$01,L93F9 / L0008 / L0007 / L93F0 / L989B",
        "symbol": "L0009 bit0; L0008; L0007",
        "address": "0x0009;0x0008;0x0007",
        "read_or_write": "read_bit_write_read",
        "value_source": "reset-in-work flag and actual position countdown/state",
        "routine_label": "L93E1",
        "init_context": "IAC motor reset in work service",
        "park_context": "reset-in-work holds desired at zero until actual reaches zero",
        "candidate_role": "iac_reset_in_work_countdown_gate",
        "actual_position_effect": "tests L0007; if nonzero exits without clearing reset-in-work",
        "desired_position_effect": "L0008 := 0 while reset is in work",
        "enable_dependency": "A/B stepping still depends on output service/enable gate elsewhere",
        "bad_shutdown_dependency": "independent; can be entered after prior reset request",
        "reset_in_work_dependency": "primary path",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "This is the clearest source proof that actual position is made trustworthy by driving toward zero during reset-in-work, then clearing the reset flag only when L0007 reaches zero",
    },
    {
        "stage": "reset_complete_seed_and_request",
        "pc": "0x93F0-0x93F6",
        "mnemonic": "BCLR/BSET/JSR",
        "operands": "L0009,#$01 / L0009,#$04 / L92A4",
        "symbol": "L0009 bit0; L0009 bit2",
        "address": "0x0009",
        "read_or_write": "bit_clear_bit_set",
        "value_source": "L0007 reached zero",
        "routine_label": "L93E1",
        "init_context": "reset-in-work completion",
        "park_context": "actual zero/home reached; request/start state marked",
        "candidate_role": "iac_reset_complete_seed",
        "actual_position_effect": "L0007 is accepted as zero/home",
        "desired_position_effect": "L0008 already zero from prior row",
        "enable_dependency": "none direct",
        "bad_shutdown_dependency": "none direct",
        "reset_in_work_dependency": "clears reset-in-work and sets R/S requested bit",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "After actual reaches zero, stock clears reset-in-work, sets R/S requested, and reseeds IAC learned/default cells through L92A4",
    },
    {
        "stage": "ignition_off_park_down_request",
        "pc": "0x93F9-0x9404",
        "mnemonic": "BRCLR/BRCLR/LDAA/JMP",
        "operands": "L0044,#$10,L940A / L0009,#$04,L9407 / L4EB0 / L9899",
        "symbol": "L0008",
        "address": "0x0008",
        "read_or_write": "write_via_L9899",
        "value_source": "L4EB0 = 145 steps IAC park down",
        "routine_label": "L93E1 -> L9899",
        "init_context": "ignition-off / R-S-requested path",
        "park_context": "commands desired target to park-down value",
        "candidate_role": "iac_park_down_desired_request",
        "actual_position_effect": "none direct; later phase logic will move actual toward desired",
        "desired_position_effect": "L0008 := L4EB0 (145)",
        "enable_dependency": "Enable gate must permit physical movement for real park motion",
        "bad_shutdown_dependency": "depends on prior R/S request state",
        "reset_in_work_dependency": "only if reset-in-work is not active and R/S requested bit is set",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "This is stock's explicit park-down desired target path; it does not directly write L0007",
    },
    {
        "stage": "cold_prior_to_start_park_request",
        "pc": "0x9517-0x9534",
        "mnemonic": "LDAA/CMPA/BCS/LDAA/JMP",
        "operands": "L0006 / L4E91 / L9531 / L4EB0 / L9899",
        "symbol": "L0008",
        "address": "0x0008",
        "read_or_write": "write_via_L9899",
        "value_source": "L4EB0 when coolant below L4E91 min-cool-for-IAC-moved-before-start",
        "routine_label": "L9537/L9531 -> L9899",
        "init_context": "not-running/startup IAC calculation",
        "park_context": "cold prior-to-start path requests park-down desired target",
        "candidate_role": "iac_cold_start_park_request",
        "actual_position_effect": "none direct",
        "desired_position_effect": "L0008 := L4EB0 (145)",
        "enable_dependency": "Enable required for physical motion",
        "bad_shutdown_dependency": "none direct",
        "reset_in_work_dependency": "none direct",
        "required_for_minimal_os": "yes_if_supporting_stock_like_cold_start_position",
        "confidence": "medium_static",
        "notes": "Static source says L4E91 is minimum coolant for IAC moved prior to start; below it, desired target becomes park-down count",
    },
    {
        "stage": "desired_position_common_sink",
        "pc": "0x9883-0x989B",
        "mnemonic": "LDX/LSRD/.../STAA/RTS",
        "operands": "#L4E92 / computed table result / L0008",
        "symbol": "L0008",
        "address": "0x0008",
        "read_or_write": "write",
        "value_source": "A from caller or computed IAC step-position table L4E92",
        "routine_label": "L9899",
        "init_context": "common desired-IAC sink",
        "park_context": "park requests enter here with A=L4EB0",
        "candidate_role": "iac_desired_position_sink",
        "actual_position_effect": "none direct",
        "desired_position_effect": "L0008 := A",
        "enable_dependency": "none direct",
        "bad_shutdown_dependency": "caller-dependent",
        "reset_in_work_dependency": "caller-dependent",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "All park/startup desired-position requests converge on STAA L0008 at L9899; this is not actual-position seeding",
    },
]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def resolve(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else repo_root() / p


def write_csv(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(ROWS)


def write_md(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# IAC Init / Park Contract",
        "",
        "## Purpose",
        "",
        "Document how stock code establishes IAC actual position and startup/crank target state.",
        "",
        "This contract does not define idle strategy and does not create an IAC writer.",
        "",
        "## Source Contracts",
        "",
        "- `IAC_IDLE_AIR_OUTPUT_CONTRACT.md`",
        "- `IAC_PHASE_SEQUENCE_CONTRACT.md`",
        "- `IAC_ENABLE_FAULT_GATE_CONTRACT.md`",
        "",
        "## Known Boundary",
        "",
        "```text",
        "L0007 = actual/present IAC position",
        "L0008 = desired/target IAC position",
        "L0009 bit0 = IAC motor reset-in-work candidate",
        "L0009 bit2 = R/S requested candidate",
        "L000A = IAC mode/output state byte",
        "L4EB0 = 145 steps IAC park down",
        "L4EB6 = 10.5 VDC minimum battery for IAC operations",
        "```",
        "",
        "## Working Hypothesis",
        "",
        "Stock code makes `L0007` trustworthy through a reset-in-work / home-to-zero process and through conservative seeding when nonvolatile memory is invalid.",
        "",
        "Park-down is not a direct actual-position write in the normal shutdown path. It is primarily a desired-position request:",
        "",
        "```text",
        "L4EB0 = 145 steps park down",
        "A = L4EB0",
        "JMP L9899",
        "L9899: STAA L0008",
        "```",
        "",
        "The actual count `L0007` then moves toward `L0008` through the already-mapped desired/actual compare and A/B phase sequence if Enable and cadence allow movement.",
        "",
        "## Required Questions",
        "",
        "- What writes `L0007` before normal idle control?",
        "- What writes `L0008` before crank/run?",
        "- Is there a park/homing overstep?",
        "- Is there a bad-shutdown recovery path?",
        "- Is there a reset-in-work skip path?",
        "- Does low voltage block park movement?",
        "- Is Enable asserted before park motion?",
        "- What value is loaded as actual after park completes?",
        "",
        "## Static Source Sequence",
        "",
        "### Startup setup call",
        "",
        "```text",
        "0x73DB  JSR L925E        ; GO SET UP IAC",
        "```",
        "",
        "### Setup routine / nonvolatile fail seed",
        "",
        "```text",
        "0x925E  LDAA L4EF2        ; 16% TPS upper limit for closed-loop IAC",
        "0x9263  STAA L0885",
        "0x9266  BRCLR L0046,#$40,L9272  ; branch if nonvolatile memory not bombed",
        "0x926A  LDAA L4EB0        ; 145 steps IAC park down",
        "0x926D  STAA L0007        ; IAC motor position",
        "0x926F  JSR L92A4         ; seed IAC learned/default cells",
        "```",
        "",
        "### Bad-shutdown branch",
        "",
        "```text",
        "0x9272  BRSET L0004,#$08,L927B  ; bad shutdown",
        "0x9276  JSR L92F1               ; normal shutdown/setup path",
        "0x927B  JSR L93C5               ; bad-shutdown setup clear",
        "```",
        "",
        "### Reset-in-work service",
        "",
        "```text",
        "0x93E1  BRCLR L0009,#$01,L93F9  ; if reset not in work, skip",
        "0x93E5  CLR L0008                ; desired target = 0 while reset is active",
        "0x93E8  TST L0007                ; actual position",
        "0x93EB  BEQ L93F0                ; if actual reached zero, finish reset",
        "0x93ED  JMP L989B                ; otherwise return and keep reset active",
        "0x93F0  BCLR L0009,#$01          ; clear reset-in-work",
        "0x93F3  BSET L0009,#$04          ; set R/S requested candidate",
        "0x93F6  JSR L92A4                ; reseed IAC learned/default cells",
        "```",
        "",
        "### Ignition-off park-down request",
        "",
        "```text",
        "0x93F9  BRCLR L0044,#$10,L940A  ; if not ignition-off, continue run/start logic",
        "0x93FD  BRCLR L0009,#$04,L9407  ; if R/S not requested, skip park request",
        "0x9401  LDAA L4EB0               ; 145 steps IAC park down",
        "0x9404  JMP L9899                ; write desired position",
        "```",
        "",
        "### Common desired-position sink",
        "",
        "```text",
        "0x9899  STAA L0008",
        "0x989B  RTS",
        "```",
        "",
        "## Static Classification",
        "",
        "```text",
        "PARK-A: partially supported",
        "  The reset-in-work path drives desired to zero until actual reaches zero. That is a homing/reset process, but physical direction and mechanical stop must be bench-proven.",
        "",
        "PARK-B: supported as a retained-state path",
        "  If nonvolatile memory is not bombed and reset-in-work is not active, stock code does not blindly overwrite L0007 at every key-on.",
        "",
        "PARK-C: supported",
        "  Bad-shutdown and reset-in-work flags change setup behavior.",
        "",
        "PARK-D: supported",
        "  Stock loads L0008 desired/target using L9899. L4EB0 park-down requests write desired, not actual.",
        "",
        "PARK-E: bench-gated",
        "  Source says IAC operations are voltage-gated elsewhere. This contract does not prove physical Enable state during park motion.",
        "",
        "PARK-F: not resolved for physical direction",
        "  Static code proves target values and flags, but bench must determine open/closed direction and real mechanical stop behavior.",
        "```",
        "",
        "## Contract Rows",
        "",
        "| Stage | PC | Instruction | Symbol | Role | Actual effect | Desired effect | Confidence |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in ROWS:
        inst = f"{row['mnemonic']} {row['operands']}".strip()
        lines.append(
            f"| {row['stage']} | `{row['pc']}` | `{inst}` | `{row['symbol']}` | {row['candidate_role']} | {row['actual_position_effect']} | {row['desired_position_effect']} | {row['confidence']} |"
        )
    lines += [
        "",
        "## Minimal-OS Requirement",
        "",
        "A minimal OS must not step the IAC based on `L0007` until `L0007` is known valid or deliberately seeded.",
        "",
        "Minimum safe options:",
        "",
        "```text",
        "Option 1: perform a stock-like reset/home sequence",
        "  set reset-in-work",
        "  command desired = 0",
        "  step until actual reaches zero or timeout/overstep is complete",
        "  clear reset-in-work",
        "  seed actual as known-home",
        "",
        "Option 2: deliberately seed actual to a conservative park-down value",
        "  L0007 := park_down_max",
        "  command desired to a known crank/start target",
        "  accept that physical agreement requires bench proof or prior park",
        "",
        "Option 3: retain previous actual position only if nonvolatile/retained RAM validity is proven",
        "```",
        "",
        "## Open Bench Questions",
        "",
        "- Does desired `0` drive the IAC closed or open physically?",
        "- Does `L4EB0 = 145` represent max-open, max-closed, or stock park-down count relative to airflow?",
        "- During reset-in-work, does the motor physically overdrive to a stop before `L0007` reaches zero?",
        "- Does `L0007` decrement/increment exactly one count per physical step during reset?",
        "- Is Enable asserted during reset/park movement, and is it blocked at low voltage?",
        "- Does bad-shutdown recovery force a new reset/home or only clear output mode state?",
        "- What crank/start desired IAC value is used after park/reset completes?",
        "",
        "## Out Of Scope For This Contract",
        "",
        "```text",
        "A/B phase order",
        "Enable voltage/fault gate",
        "closed-loop idle strategy",
        "desired idle RPM calculation",
        "IAC writer implementation",
        "calibration-source indexing",
        "```",
        "",
        "## Next Contract",
        "",
        "After this pass, the IAC side is ready for a source-side boundary README:",
        "",
        "```text",
        "source/minimal_os/iac/README.md",
        "```",
        "",
        "The calibration side remains parked until:",
        "",
        "```text",
        "CALIBRATION_SOURCE_INDEX",
        "```",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--source", default="source/31/BMHM_HAC_ORG_7100_to_end.asm")
    p.add_argument("--phase", default="maps/contracts/iac_phase_sequence_contract.csv")
    p.add_argument("--enable", default="maps/contracts/iac_enable_fault_gate_contract.csv")
    p.add_argument("--out-md", required=True)
    p.add_argument("--out-csv", required=True)
    args = p.parse_args()
    write_csv(resolve(args.out_csv))
    write_md(resolve(args.out_md))
    print(f"IAC_INIT_PARK: wrote {len(ROWS)} init/park rows")
    return 0


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def resolve(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else repo_root() / p


if __name__ == "__main__":
    raise SystemExit(main())
