#!/usr/bin/env python3
"""Build the IAC Enable/Fault Gate contract.

This isolates the source-proven Enable candidate path:

    L000A bit4 -> L004C bit4 -> L3062 bit4

It does not define A/B phase order, park/reset movement, desired IAC
calculation, idle strategy, or create an IAC writer.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

FIELDS = [
    "stage", "pc", "mnemonic", "operands", "symbol", "address", "read_or_write",
    "bitmask", "value_source", "routine_label", "enable_context", "candidate_role",
    "enable_condition", "disable_condition", "voltage_gate_candidate",
    "fault_gate_candidate", "test_reset_candidate", "required_for_minimal_os",
    "confidence", "notes",
]

ROWS = [
    {
        "stage": "load_enable_mode_byte",
        "pc": "0x91A3",
        "mnemonic": "LDAB",
        "operands": "L000A",
        "symbol": "L000A bit4",
        "address": "0x000A",
        "read_or_write": "read",
        "bitmask": "0x10",
        "value_source": "IAC mode/output state byte",
        "routine_label": "L91A3",
        "enable_context": "IAC output update entry",
        "candidate_role": "iac_enable_bit",
        "enable_condition": "preserved until voltage/status gate decides",
        "disable_condition": "may be cleared by voltage/setup gates",
        "voltage_gate_candidate": "pending next rows",
        "fault_gate_candidate": "pending",
        "test_reset_candidate": "pending",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "bit4 is carried in the same mode byte as IAC direction and A/B phase bits",
    },
    {
        "stage": "load_battery_voltage",
        "pc": "0x91A5",
        "mnemonic": "LDAA",
        "operands": "L00A7",
        "symbol": "L00A7",
        "address": "0x00A7",
        "read_or_write": "read",
        "bitmask": "",
        "value_source": "BAT VOLTS, VDC/10",
        "routine_label": "L91A3",
        "enable_context": "voltage gate input",
        "candidate_role": "iac_voltage_sufficient_gate",
        "enable_condition": "voltage value loaded for comparison",
        "disable_condition": "out-of-range voltage branches clear/skip enable",
        "voltage_gate_candidate": "battery voltage source proven: L00A7",
        "fault_gate_candidate": "not_fault",
        "test_reset_candidate": "not_reset",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "source comment identifies L00A7 as BAT VOLTS, VDC/10",
    },
    {
        "stage": "high_voltage_threshold",
        "pc": "0x91A7-0x91AD",
        "mnemonic": "CMPA/BLS/ANDB/BRA",
        "operands": "#169 / L91AF / #$EF / L91B8",
        "symbol": "L000A bit4",
        "address": "0x000A",
        "read_or_write": "clear_candidate",
        "bitmask": "0x10 clear via 0xEF",
        "value_source": "L00A7 battery volts compared with #169",
        "routine_label": "L91A3",
        "enable_context": "high-voltage protection gate",
        "candidate_role": "iac_enable_clear",
        "enable_condition": "L00A7 <= 169 continues to normal gate",
        "disable_condition": "L00A7 > 169 clears bit4 and sets low-battery/protection flag path",
        "voltage_gate_candidate": "16.9 V upper/invalid threshold candidate",
        "fault_gate_candidate": "driver protection candidate",
        "test_reset_candidate": "not_reset",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "#169 is explicitly commented 16.9 VDC; ANDB #$EF clears the 0x10 Enable candidate",
    },
    {
        "stage": "ignition_off_bypass_gate",
        "pc": "0x91AF",
        "mnemonic": "BRSET",
        "operands": "L0044,#$10,L91BD",
        "symbol": "L0044 bit4",
        "address": "0x0044",
        "read_or_write": "read_bit",
        "bitmask": "0x10",
        "value_source": "IGNITION OFF flag/comment",
        "routine_label": "L91A3",
        "enable_context": "startup/shutdown mode gate",
        "candidate_role": "iac_enable_set",
        "enable_condition": "L0044 bit4 set branches to enable/good path",
        "disable_condition": "if not set, low-voltage threshold L4EB6 is checked",
        "voltage_gate_candidate": "secondary gate follows",
        "fault_gate_candidate": "not_fault",
        "test_reset_candidate": "startup_shutdown_candidate",
        "required_for_minimal_os": "yes",
        "confidence": "medium_static",
        "notes": "source comment says ignition off; behavior may support shutdown/park conditions, not normal run only",
    },
    {
        "stage": "low_voltage_threshold",
        "pc": "0x91B3-0x91B8",
        "mnemonic": "CMPA/BHI/BSET",
        "operands": "L4EB6 / L91BD / L003E,#$04",
        "symbol": "L4EB6; L003E bit2",
        "address": "calibration; 0x003E",
        "read_or_write": "read_compare_then_set_flag",
        "bitmask": "0x04",
        "value_source": "L00A7 battery volts compared with low threshold L4EB6",
        "routine_label": "L91A3",
        "enable_context": "low-voltage disable/protection gate",
        "candidate_role": "iac_voltage_low_disable",
        "enable_condition": "L00A7 > L4EB6 branches to good path and sets Enable",
        "disable_condition": "L00A7 <= L4EB6 sets L003E bit2 low battery and skips ORAB #$10",
        "voltage_gate_candidate": "low-voltage threshold candidate",
        "fault_gate_candidate": "low battery flag L003E bit2",
        "test_reset_candidate": "not_reset",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "low-voltage path does not explicitly clear bit4 here unless already clear; it skips setting Enable and commits current B at L9200",
    },
    {
        "stage": "good_voltage_enable_set",
        "pc": "0x91BD-0x91C0",
        "mnemonic": "BCLR/ORAB",
        "operands": "L003E,#$04 / #$10",
        "symbol": "L000A bit4; L003E bit2",
        "address": "0x000A; 0x003E",
        "read_or_write": "set_candidate",
        "bitmask": "0x10 set; 0x04 clear",
        "value_source": "good voltage/status path",
        "routine_label": "L91A3",
        "enable_context": "enable asserted path",
        "candidate_role": "iac_enable_set",
        "enable_condition": "voltage/status gate passes",
        "disable_condition": "not applicable in this row",
        "voltage_gate_candidate": "voltage sufficient",
        "fault_gate_candidate": "clears low battery flag",
        "test_reset_candidate": "not_reset",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "ORAB #$10 sets the Enable candidate before desired/actual/phase logic proceeds",
    },
    {
        "stage": "no_step_enable_refresh",
        "pc": "0x91C2-0x91CA",
        "mnemonic": "LDAA/CMPA/BNE/ANDB/BRA",
        "operands": "L0007 / L0008 / L91CC / #$FE / L9200",
        "symbol": "L000A bit4",
        "address": "0x000A",
        "read_or_write": "preserve",
        "bitmask": "0x10 preserved",
        "value_source": "B after enable gate",
        "routine_label": "L91A3",
        "enable_context": "desired==actual/no-step path",
        "candidate_role": "iac_enable_bit",
        "enable_condition": "Enable remains set if voltage/status gate passed",
        "disable_condition": "no-step does not clear Enable",
        "voltage_gate_candidate": "already decided before compare",
        "fault_gate_candidate": "not_fault",
        "test_reset_candidate": "not_reset",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "desired==actual clears direction bit0 only; bit4 remains governed by earlier enable gate",
    },
    {
        "stage": "mode_byte_commit",
        "pc": "0x9200",
        "mnemonic": "STAB",
        "operands": "L000A",
        "symbol": "L000A bit4",
        "address": "0x000A",
        "read_or_write": "write",
        "bitmask": "0x10",
        "value_source": "B after voltage/status/phase logic",
        "routine_label": "L91A3",
        "enable_context": "mode byte commit",
        "candidate_role": "iac_enable_bit",
        "enable_condition": "committed if set in B",
        "disable_condition": "committed clear if cleared/skipped",
        "voltage_gate_candidate": "yes",
        "fault_gate_candidate": "yes via L003E bit2 and setup path",
        "test_reset_candidate": "possible via L93C5 setup clear",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "Enable is stored with direction and A/B phase state in L000A",
    },
    {
        "stage": "shadow_field_update",
        "pc": "0x9203-0x920A",
        "mnemonic": "LDAA/ANDA/ANDB/ABA/STAA",
        "operands": "L004C / #$E3 / #$1C / L004C",
        "symbol": "L004C bit4",
        "address": "0x004C",
        "read_or_write": "write_shadow",
        "bitmask": "0x10 within 0x1C field",
        "value_source": "L000A bits2/3/4 inserted into L004C bits2/3/4",
        "routine_label": "L91A3",
        "enable_context": "output shadow update",
        "candidate_role": "iac_output_shadow_update",
        "enable_condition": "L000A bit4 copied into L004C bit4",
        "disable_condition": "cleared L000A bit4 clears L004C bit4",
        "voltage_gate_candidate": "already resolved into L000A",
        "fault_gate_candidate": "reflected in shadow",
        "test_reset_candidate": "reflected in shadow",
        "required_for_minimal_os": "yes",
        "confidence": "high_static",
        "notes": "Enable is updated atomically with A/B shadow field bits2/3/4",
    },
    {
        "stage": "hardware_latch_write",
        "pc": "0xF40F-0xF411",
        "mnemonic": "LDAA/STAA",
        "operands": "L004C / L3062",
        "symbol": "L3062 bit4 candidate",
        "address": "0x3062",
        "read_or_write": "write_latch",
        "bitmask": "0x10 candidate",
        "value_source": "L004C output shadow",
        "routine_label": "LF400",
        "enable_context": "board output latch service",
        "candidate_role": "iac_latch_write",
        "enable_condition": "physical bit4 follows L004C bit4 if mapping is correct",
        "disable_condition": "physical bit4 clears with L004C bit4 if mapping is correct",
        "voltage_gate_candidate": "reflected through L004C",
        "fault_gate_candidate": "reflected through L004C",
        "test_reset_candidate": "reflected through L004C",
        "required_for_minimal_os": "yes_bench_pin_mapping_pending",
        "confidence": "high_static_for_latch_write_medium_for_physical_enable",
        "notes": "bench must confirm L3062 bit4 is the physical IAC Enable input",
    },
    {
        "stage": "bad_shutdown_setup_clear",
        "pc": "0x9272-0x927B;0x93C5-0x93CD",
        "mnemonic": "BRSET/JSR/LDAA/ANDA/STAA",
        "operands": "L0004,#$08,L927B / L93C5 / L000A / #$0C / L000A",
        "symbol": "L000A bit4",
        "address": "0x000A",
        "read_or_write": "clear_candidate",
        "bitmask": "0x10 cleared by ANDA #$0C",
        "value_source": "bad shutdown/setup path if IAC reset not in work",
        "routine_label": "L925E/L93C5",
        "enable_context": "startup/setup clear path",
        "candidate_role": "iac_reset_disable",
        "enable_condition": "not enabled by this path",
        "disable_condition": "if L0009 bit0 clear, L000A is reduced to A/B bits only, clearing Enable and direction",
        "voltage_gate_candidate": "not_voltage",
        "fault_gate_candidate": "bad shutdown candidate L0004 bit3",
        "test_reset_candidate": "startup/reset/setup path",
        "required_for_minimal_os": "yes_for_init_policy",
        "confidence": "high_static",
        "notes": "L93C5 preserves bits2/3 and clears bit4; called from bad-shutdown setup path",
    },
]


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def resolve(path: str | Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else repo_root() / p


def write_csv(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(ROWS)


def write_md(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# IAC Enable / Fault Gate Contract",
        "",
        "## Purpose",
        "",
        "Document the enable/disable logic for the IAC driver command path.",
        "",
        "This contract covers only the Enable path. It does not define A/B phase order, park/reset movement, desired IAC calculation, idle strategy, or create an IAC writer.",
        "",
        "## Known Boundary",
        "",
        "Phase command path is owned by:",
        "",
        "- `IAC_PHASE_SEQUENCE_CONTRACT.md`",
        "",
        "This contract owns:",
        "",
        "```text",
        "L000A bit4",
        "→ L004C bit4",
        "→ L3062 bit4 candidate",
        "```",
        "",
        "## Working Hypothesis",
        "",
        "IAC Enable is a driver-enable / health gate, not a per-step pulse.",
        "",
        "It likely asserts after startup voltage/driver conditions are acceptable and remains asserted during normal operation. It may clear for low/high voltage, bad shutdown/setup, reset, test, or protection behavior.",
        "",
        "## Static Clues",
        "",
        "| Clue | Candidate meaning | Static result |",
        "|---|---|---|",
        "| `LDAA L00A7` | battery voltage source | source comment: `BAT VOLTS, VDC/10` |",
        "| `CMPA #169` | high-voltage threshold | source comment: `16.9 VDC` |",
        "| `ANDB #$EF` | clear Enable bit | clears bit4 candidate |",
        "| `ORAB #$10` | set Enable bit | sets bit4 candidate |",
        "| `BSET L003E,#$04` | low-battery/protection flag | set when voltage gate fails |",
        "| `BCLR L003E,#$04` | clear low-battery/protection flag | good path before Enable set |",
        "| `ANDA #$0C` in `L93C5` | setup clear | preserves A/B bits, clears Enable and direction |",
        "| `L004C -> L3062` | full output latch write | physical pin mapping bench-gated |",
        "",
        "## Source-Proven Enable Chain",
        "",
        "```text",
        "0x91A3  LDAB L000A       ; mode/output byte",
        "0x91A5  LDAA L00A7       ; BAT VOLTS, VDC/10",
        "0x91A7  CMPA #169        ; 16.9 VDC threshold",
        "0x91AB  ANDB #$EF        ; clear bit4 candidate if above threshold",
        "",
        "0x91B3  CMPA L4EB6       ; low-voltage threshold candidate",
        "0x91B8  BSET L003E,#$04  ; set low battery/protection flag",
        "",
        "0x91BD  BCLR L003E,#$04  ; clear low battery/protection flag",
        "0x91C0  ORAB #$10        ; set bit4 candidate",
        "",
        "0x9200  STAB L000A       ; commit mode byte",
        "0x9203  LDAA L004C",
        "0x9205  ANDA #$E3        ; clear bits2/3/4 in output shadow",
        "0x9207  ANDB #$1C        ; isolate L000A bits2/3/4",
        "0x920A  STAA L004C       ; commit output shadow",
        "",
        "0xF40F  LDAA L004C",
        "0xF411  STAA L3062       ; full-byte hardware latch write",
        "```",
        "",
        "## Enable Decision Model",
        "",
        "```text",
        "if L00A7 > 169:",
        "  clear L000A bit4 candidate",
        "  set L003E bit2 low-battery/protection flag path",
        "  skip phase/update compare",
        "",
        "else if L0044 bit4 set:",
        "  clear L003E bit2",
        "  set L000A bit4 candidate",
        "",
        "else if L00A7 > L4EB6:",
        "  clear L003E bit2",
        "  set L000A bit4 candidate",
        "",
        "else:",
        "  set L003E bit2 low-battery/protection flag",
        "  skip ORAB #$10",
        "```",
        "",
        "Current interpretation: `L00A7` is proven as the compared variable. `#169` is the high voltage threshold candidate. `L4EB6` is the low voltage threshold candidate. `L003E bit2` is the low-battery/protection flag associated with this gate.",
        "",
        "## Enable Is Not Step-Pulsed In The Source Path",
        "",
        "When `desired == actual`, the no-step path clears direction bit0 but does not clear bit4. Therefore Enable remains governed by the voltage/status gate, not by step demand.",
        "",
        "If the voltage gate fails, the code branches to `L9200` before desired/actual compare and A/B ring update. That means the source path can hold/commit mode state without stepping when Enable is not allowed.",
        "",
        "## Setup / Bad-Shutdown Clear Path",
        "",
        "A separate setup path calls `L93C5` from the bad-shutdown branch:",
        "",
        "```text",
        "0x9272  BRSET L0004,#$08,L927B   ; bad shutdown candidate",
        "0x927B  JSR L93C5",
        "",
        "0x93C5  BRSET L0009,#$01,L93CF   ; skip if IAC reset in work",
        "0x93C9  LDAA L000A",
        "0x93CB  ANDA #$0C                ; preserve A/B only",
        "0x93CD  STAA L000A               ; clear Enable and direction",
        "```",
        "",
        "This supports treating Enable as a startup/setup/fault gate rather than a per-step pulse.",
        "",
        "## Contract Rows",
        "",
        "| Stage | PC | Instruction | Symbol | Role | Enable condition | Disable condition | Confidence |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in ROWS:
        inst = f"{row['mnemonic']} {row['operands']}".strip()
        lines.append(
            f"| {row['stage']} | `{row['pc']}` | `{inst}` | `{row['symbol']}` | {row['candidate_role']} | {row['enable_condition']} | {row['disable_condition']} | {row['confidence']} |"
        )
    lines += [
        "",
        "## Required New-OS Behavior",
        "",
        "A future IAC module must reproduce or explicitly replace:",
        "",
        "1. battery/driver voltage qualification before asserting Enable",
        "2. bit4 set/clear behavior in the IAC mode byte",
        "3. `L000A bit4 -> L004C bit4` shadow propagation",
        "4. `L004C -> L3062` physical latch behavior if bit4 is confirmed as Enable",
        "5. setup/bad-shutdown clear behavior or an equivalent safe default",
        "6. low-battery/protection flag behavior if it affects other modules",
        "",
        "## Open Bench Questions",
        "",
        "- Is `L3062 bit4` physically the IAC driver Enable pin?",
        "- Does Enable remain asserted while A/B holds or steps normally?",
        "- Does high-voltage or low-voltage testing deassert the physical Enable pin?",
        "- Does a setup/bad-shutdown clear produce a physical Enable deassertion?",
        "- Does clearing Enable prevent physical IAC motion even if A/B bits change?",
        "- Does the external driver have additional health/fault behavior not visible in source?",
        "",
        "## Out Of Scope For This Contract",
        "",
        "```text",
        "A/B phase sequence",
        "park/reset/home movement",
        "desired IAC calculation",
        "idle-speed strategy",
        "step cadence/rate-limit equation",
        "IAC writer implementation",
        "```",
        "",
        "## Next Contract",
        "",
        "```text",
        "IAC_INIT_PARK_CONTRACT",
        "```",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--source", default="source/31/BMHM_HAC_ORG_7100_to_end.asm")
    p.add_argument("--iac", default="maps/contracts/iac_idle_air_output_contract.csv")
    p.add_argument("--phase", default="maps/contracts/iac_phase_sequence_contract.csv")
    p.add_argument("--out-md", required=True)
    p.add_argument("--out-csv", required=True)
    args = p.parse_args()
    write_csv(resolve(args.out_csv))
    write_md(resolve(args.out_md))
    print(f"IAC_ENABLE_FAULT_GATE: wrote {len(ROWS)} enable/fault rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
